
package com.optum.rqns.services.hichistory;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.optum.rqns.services.hichistory.ServiceException_Exception;
import com.optum.rqns.services.utils.DataBaseConnect;



/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-25T16:45:51.746+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class HicHistoryService_HicHistoryServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "hicHistoryService");
   
    public HicHistoryService_HicHistoryServiceImplPort_Client() {
    }

    public  String hicServiceCallStage() throws java.lang.Exception {
    	String msg="";
    	
        String sHic = null;
        String sMstrHic = null;
        URL wsdlURL = HicHistoryService_Service.WSDL_LOCATION;
      
      
        HicHistoryService_Service ss = new HicHistoryService_Service(wsdlURL, SERVICE_NAME);
        HicHistoryService port = ss.getHicHistoryServiceImplPort();  
        
        {
        System.out.println("Invoking getHicHistory...");
        String sRequestSql="select hic_num,hic_mstr_id from mstr_hic_eff_dt_adj  order by updt_dttm desc";
        
        ResultSet rs=DataBaseConnect.getRsList("STAGE", sRequestSql);
        int iCount=0;
         while (rs.next()){
        	 sHic = rs.getString(1);
        	 sMstrHic = rs.getString(2);
         	break;
         }
        java.lang.String _getHicHistory_hicNumber = sHic;
        com.optum.rqns.services.hichistory.ServiceMetaData _getHicHistory_metaData = new com.optum.rqns.services.hichistory.ServiceMetaData();
        _getHicHistory_metaData.setAppId("5317c8af4dd6bec7b46c2083018b8ae6");
        String sResponseSql="select count(*) as count from   mstr_hic_eff_dt_adj where hic_mstr_id='"+sMstrHic+"'";
        System.out.println(sResponseSql);
        ResultSet rs1=DataBaseConnect.getRsList("STAGE", sResponseSql);
         iCount=0;
        while (rs1.next()){
        	iCount = rs1.getInt("count");
        	break;
        }
        javax.xml.ws.Holder<java.lang.String> _getHicHistory_inputHicNumber = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.Integer> _getHicHistory_hicCount = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.util.List<com.optum.rqns.services.hichistory.HicDetails>> _getHicHistory_hicDetails = new javax.xml.ws.Holder<java.util.List<com.optum.rqns.services.hichistory.HicDetails>>();
        javax.xml.ws.Holder<java.lang.String> _getHicHistory_errorMsg = new javax.xml.ws.Holder<java.lang.String>();
        try {
            port.getHicHistory(_getHicHistory_hicNumber, _getHicHistory_metaData, _getHicHistory_inputHicNumber, _getHicHistory_hicCount, _getHicHistory_hicDetails, _getHicHistory_errorMsg);

            System.out.println("getHicHistory._getHicHistory_inputHicNumber=" + _getHicHistory_inputHicNumber.value);
            System.out.println("getHicHistory._getHicHistory_hicCount=" + _getHicHistory_hicCount.value);
            System.out.println("getHicHistory._getHicHistory_hicDetails=" + _getHicHistory_hicDetails.value);
            System.out.println("getHicHistory._getHicHistory_errorMsg=" + _getHicHistory_errorMsg.value);
            if (_getHicHistory_hicCount.value.equals(iCount) && _getHicHistory_inputHicNumber.value.equals(sHic))
            {
            	msg="Response --------  getHicHistory._getHicHistory_inputHicNumber=" + _getHicHistory_inputHicNumber.value;
            	msg= msg+ " getHicHistory._getHicHistory_hicCount=" + _getHicHistory_hicCount.value;
            	msg= msg+ " getHicHistory._getHicHistory_hicDetails=" + _getHicHistory_hicDetails.value;
            	msg= msg+ " getHicHistory._getHicHistory_errorMsg=" + _getHicHistory_hicDetails.value;
            }
        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
            msg=e.toString();
        }
        System.out.println(msg);
            }

        //System.exit(0);
        return(msg) ;
    }

}
