package com.optum.rqns.services.gapTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * The service port type for GapStatusInfoService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-02T12:46:32.455+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://services.rqns.optum.com/", name = "GapStatusInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface GapStatusInfoService {

    /**
     * The operation saves GapStatus information
     */
    @WebMethod(action = "addGapStatusInfo")
    @RequestWrapper(localName = "addGapStatusInfo", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.gapTest.AddGapStatusInfo")
    @ResponseWrapper(localName = "addGapStatusInfoResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.gapTest.AddGapStatusInfoResponse")
    public void addGapStatusInfo(
        @WebParam(name = "serviceMetaData", targetNamespace = "")
        com.optum.rqns.services.gapTest.ServiceMetaData serviceMetaData,
        @WebParam(name = "gapStatusInfo", targetNamespace = "")
        com.optum.rqns.services.gapTest.GapStatusInfo gapStatusInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> responseCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseMessage", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> responseMessage
    ) throws ServiceException_Exception;
}
