
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.demography;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-25T16:44:56.514+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "AcaMemberDemographicService",
                      portName = "AcaMemberDemographicServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/rqns-services-web/services/AcaMemberDemographicService?wsdl",
                      endpointInterface = "com.optum.rqns.services.demography.AcaMemberDemographicService")
                      
public class AcaMemberDemographicServiceImpl implements AcaMemberDemographicService {

    private static final Logger LOG = Logger.getLogger(AcaMemberDemographicServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.demography.AcaMemberDemographicService#getAcaMemberDemographicInfoByMbrIDAndClient(java.lang.String  memberID ,)java.lang.String  modifierID ,)java.lang.String  clientName ,)com.optum.rqns.services.demography.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.demography.AcaMemberDemographicInfo getAcaMemberDemographicInfoByMbrIDAndClient(java.lang.String memberID,java.lang.String modifierID,java.lang.String clientName,com.optum.rqns.services.demography.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getAcaMemberDemographicInfoByMbrIDAndClient");
        System.out.println(memberID);
        System.out.println(modifierID);
        System.out.println(clientName);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.demography.AcaMemberDemographicInfo _return = new com.optum.rqns.services.demography.AcaMemberDemographicInfo();
            _return.setReturnCode(877169989);
            _return.setReturnCodeDesc("ReturnCodeDesc-1926223065");
            _return.setSource("Source1446559459");
            java.util.List<com.optum.rqns.services.demography.AcaMemberDemographicDetails> _returnAcaMemberDemographicDetails = new java.util.ArrayList<com.optum.rqns.services.demography.AcaMemberDemographicDetails>();
            com.optum.rqns.services.demography.AcaMemberDemographicDetails _returnAcaMemberDemographicDetailsVal1 = new com.optum.rqns.services.demography.AcaMemberDemographicDetails();
            _returnAcaMemberDemographicDetailsVal1.setClientGuid("ClientGuid1256632384");
            _returnAcaMemberDemographicDetailsVal1.setMemberID("MemberID796733317");
            _returnAcaMemberDemographicDetailsVal1.setMemberIDModifier("MemberIDModifier-1296929346");
            _returnAcaMemberDemographicDetailsVal1.setGlobalMemberID("GlobalMemberID1481195604");
            _returnAcaMemberDemographicDetailsVal1.setPlanNumber("PlanNumber261613967");
            _returnAcaMemberDemographicDetailsVal1.setSubscriberID("SubscriberID-1854742494");
            _returnAcaMemberDemographicDetailsVal1.setFirstName("FirstName-928507253");
            _returnAcaMemberDemographicDetailsVal1.setMiddleName("MiddleName-1763042278");
            _returnAcaMemberDemographicDetailsVal1.setLastName("LastName-1825649386");
            _returnAcaMemberDemographicDetailsVal1.setOriginalStartDate("OriginalStartDate1655080987");
            _returnAcaMemberDemographicDetailsVal1.setLatestEndDate("LatestEndDate-852198053");
            _returnAcaMemberDemographicDetailsVal1.setHomePhone("HomePhone985031185");
            _returnAcaMemberDemographicDetailsVal1.setAddressLine1("AddressLine1-575477167");
            _returnAcaMemberDemographicDetailsVal1.setAddressLine2("AddressLine2-657340917");
            _returnAcaMemberDemographicDetailsVal1.setAddressCity("AddressCity-97531353");
            _returnAcaMemberDemographicDetailsVal1.setAddressState("AddressState-400579365");
            _returnAcaMemberDemographicDetailsVal1.setAddressZipcode("AddressZipcode1734922187");
            _returnAcaMemberDemographicDetailsVal1.setDateOfBirth("DateOfBirth1549632906");
            _returnAcaMemberDemographicDetailsVal1.setGender("Gender1394961065");
            _returnAcaMemberDemographicDetailsVal1.setUCardID("UCardID-1965557280");
            _returnAcaMemberDemographicDetails.add(_returnAcaMemberDemographicDetailsVal1);
            _return.getAcaMemberDemographicDetails().addAll(_returnAcaMemberDemographicDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.demography.AcaMemberDemographicService#getAcaMemberDemographicInfoByGlbMbrIDAndClient(java.lang.String  globalMemberID ,)java.lang.String  clientName ,)com.optum.rqns.services.demography.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.demography.AcaMemberDemographicInfo getAcaMemberDemographicInfoByGlbMbrIDAndClient(java.lang.String globalMemberID,java.lang.String clientName,com.optum.rqns.services.demography.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getAcaMemberDemographicInfoByGlbMbrIDAndClient");
        System.out.println(globalMemberID);
        System.out.println(clientName);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.demography.AcaMemberDemographicInfo _return = new com.optum.rqns.services.demography.AcaMemberDemographicInfo();
            _return.setReturnCode(1822926036);
            _return.setReturnCodeDesc("ReturnCodeDesc-329504558");
            _return.setSource("Source-1821306574");
            java.util.List<com.optum.rqns.services.demography.AcaMemberDemographicDetails> _returnAcaMemberDemographicDetails = new java.util.ArrayList<com.optum.rqns.services.demography.AcaMemberDemographicDetails>();
            com.optum.rqns.services.demography.AcaMemberDemographicDetails _returnAcaMemberDemographicDetailsVal1 = new com.optum.rqns.services.demography.AcaMemberDemographicDetails();
            _returnAcaMemberDemographicDetailsVal1.setClientGuid("ClientGuid177042838");
            _returnAcaMemberDemographicDetailsVal1.setMemberID("MemberID-637392272");
            _returnAcaMemberDemographicDetailsVal1.setMemberIDModifier("MemberIDModifier-70637403");
            _returnAcaMemberDemographicDetailsVal1.setGlobalMemberID("GlobalMemberID-1868979014");
            _returnAcaMemberDemographicDetailsVal1.setPlanNumber("PlanNumber-701847550");
            _returnAcaMemberDemographicDetailsVal1.setSubscriberID("SubscriberID-934652015");
            _returnAcaMemberDemographicDetailsVal1.setFirstName("FirstName-1788981650");
            _returnAcaMemberDemographicDetailsVal1.setMiddleName("MiddleName1600543288");
            _returnAcaMemberDemographicDetailsVal1.setLastName("LastName-737944195");
            _returnAcaMemberDemographicDetailsVal1.setOriginalStartDate("OriginalStartDate347473033");
            _returnAcaMemberDemographicDetailsVal1.setLatestEndDate("LatestEndDate-1138692954");
            _returnAcaMemberDemographicDetailsVal1.setHomePhone("HomePhone85692212");
            _returnAcaMemberDemographicDetailsVal1.setAddressLine1("AddressLine11569793979");
            _returnAcaMemberDemographicDetailsVal1.setAddressLine2("AddressLine22061392313");
            _returnAcaMemberDemographicDetailsVal1.setAddressCity("AddressCity546552185");
            _returnAcaMemberDemographicDetailsVal1.setAddressState("AddressState789723545");
            _returnAcaMemberDemographicDetailsVal1.setAddressZipcode("AddressZipcode1758556937");
            _returnAcaMemberDemographicDetailsVal1.setDateOfBirth("DateOfBirth-876939890");
            _returnAcaMemberDemographicDetailsVal1.setGender("Gender-1029034072");
            _returnAcaMemberDemographicDetailsVal1.setUCardID("UCardID1521877199");
            _returnAcaMemberDemographicDetails.add(_returnAcaMemberDemographicDetailsVal1);
            _return.getAcaMemberDemographicDetails().addAll(_returnAcaMemberDemographicDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
