package com.optum.rqns.services.demography;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * The service port type for AcaMemberDemographicService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-25T16:44:56.529+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://services.rqns.optum.com/", name = "AcaMemberDemographicService")
@XmlSeeAlso({ObjectFactory.class})
public interface AcaMemberDemographicService {

    /**
     * The operation fetches member demographics information by member id and client name
     */
    @WebMethod(action = "getAcaMemberDemographicInfoByMbrIDAndClient")
    @RequestWrapper(localName = "getAcaMemberDemographicInfoByMbrIDAndClient", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.demography.GetAcaMemberDemographicInfoByMbrIDAndClient")
    @ResponseWrapper(localName = "getAcaMemberDemographicInfoByMbrIDAndClientResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.demography.GetAcaMemberDemographicInfoByMbrIDAndClientResponse")
    @WebResult(name = "acaMemberDemographicInfo", targetNamespace = "")
    public com.optum.rqns.services.demography.AcaMemberDemographicInfo getAcaMemberDemographicInfoByMbrIDAndClient(
        @WebParam(name = "memberID", targetNamespace = "")
        java.lang.String memberID,
        @WebParam(name = "modifierID", targetNamespace = "")
        java.lang.String modifierID,
        @WebParam(name = "clientName", targetNamespace = "")
        java.lang.String clientName,
        @WebParam(name = "metaData", targetNamespace = "")
        com.optum.rqns.services.demography.ServiceMetaData metaData
    ) throws ServiceException_Exception;

    /**
     * The operation fetches member demographics information by global member id and client name
     */
    @WebMethod(action = "getAcaMemberDemographicInfoByGlbMbrIDAndClient")
    @RequestWrapper(localName = "getAcaMemberDemographicInfoByGlbMbrIDAndClient", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.demography.GetAcaMemberDemographicInfoByGlbMbrIDAndClient")
    @ResponseWrapper(localName = "getAcaMemberDemographicInfoByGlbMbrIDAndClientResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.demography.GetAcaMemberDemographicInfoByGlbMbrIDAndClientResponse")
    @WebResult(name = "acaMemberDemographicInfo", targetNamespace = "")
    public com.optum.rqns.services.demography.AcaMemberDemographicInfo getAcaMemberDemographicInfoByGlbMbrIDAndClient(
        @WebParam(name = "globalMemberID", targetNamespace = "")
        java.lang.String globalMemberID,
        @WebParam(name = "clientName", targetNamespace = "")
        java.lang.String clientName,
        @WebParam(name = "metaData", targetNamespace = "")
        com.optum.rqns.services.demography.ServiceMetaData metaData
    ) throws ServiceException_Exception;
}
