package com.optum.rqns.services.medicareEligiblity2Test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * The service port type for MemberEligibilityService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T15:16:28.989+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://services.rqns.optum.com/", name = "MemberEligibilityServicev2")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MemberEligibilityServicev2 {

    /**
     * The operation fetches members eligibility information by hic id and date range
     */
    @WebMethod(action = "getEligibleMembers")
    @WebResult(name = "getEligibleMembersResponse", targetNamespace = "http://services.rqns.optum.com/", partName = "getEligibleMembersResponse")
    public GetEligibleMembersResponsev2 getEligibleMembers(
        @WebParam(partName = "getEligibleMembers", name = "getEligibleMembers", targetNamespace = "http://services.rqns.optum.com/")
        GetEligibleMembers getEligibleMembers
    ) throws ServiceException_Exception;
}
