
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.medicaideligiblityTest;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-27T18:24:48.364+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "medicaidMemberEligibilityService",
                      portName = "MedicaidMemberEligibilityServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/medicaidMemberEligibilityService?wsdl",
                      endpointInterface = "com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityService")
                      
public class MedicaidMemberEligibilityServiceImpl implements MedicaidMemberEligibilityService {

    private static final Logger LOG = Logger.getLogger(MedicaidMemberEligibilityServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityService#getEligibleMcaidMembersByGlbMbrIDAndClient(com.optum.rqns.services.medicaideligiblityTest.GetEligibleMcaidMembersByGlbMbrIDAndClient  getEligibleMcaidMembersByGlbMbrIDAndClient )*
     */
    public com.optum.rqns.services.medicaideligiblityTest.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse getEligibleMcaidMembersByGlbMbrIDAndClient(GetEligibleMcaidMembersByGlbMbrIDAndClient getEligibleMcaidMembersByGlbMbrIDAndClient) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleMcaidMembersByGlbMbrIDAndClient");
        System.out.println(getEligibleMcaidMembersByGlbMbrIDAndClient);
        try {
            com.optum.rqns.services.medicaideligiblityTest.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse _return = new com.optum.rqns.services.medicaideligiblityTest.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse();
            com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityInfo _returnEligibilityInfo = new com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityDetails> _returnEligibilityInfoMedicaidMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityDetails>();
            com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityDetails _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1 = new com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityDetails();
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setReturnCode(1573073638);
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc2113240979");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource335382846");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setMemberID("MemberID-1046506539");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setModifierID("ModifierID240872886");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID1261442908");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber1076449465");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setPlanDesc("PlanDesc-828621723");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setLobID("LobID1043952910");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setLobIDDesc("LobIDDesc-1752622212");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setProgramTypeCd("ProgramTypeCd-1762499085");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setClassID("ClassID2004609201");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setClassIDDesc("ClassIDDesc154576473");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt283111038");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt-1677736611");
            _returnEligibilityInfoMedicaidMemberEligibilityDetails.add(_returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1);
            _returnEligibilityInfo.getMedicaidMemberEligibilityDetails().addAll(_returnEligibilityInfoMedicaidMemberEligibilityDetails);
            _returnEligibilityInfo.setErrorMsg("ErrorMsg-1319957691");
            _return.setEligibilityInfo(_returnEligibilityInfo);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityService#getEligibleMcaidMembersByMbrIDAndClient(java.lang.String  eligStrtDt ,)java.lang.String  eligEndDt ,)java.lang.String  clientName ,)java.lang.String  memberID ,)java.lang.String  modifierID ,)com.optum.rqns.services.medicaideligiblityTest.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityInfo getEligibleMcaidMembersByMbrIDAndClient(java.lang.String eligStrtDt,java.lang.String eligEndDt,java.lang.String clientName,java.lang.String memberID,java.lang.String modifierID,com.optum.rqns.services.medicaideligiblityTest.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleMcaidMembersByMbrIDAndClient");
        System.out.println(eligStrtDt);
        System.out.println(eligEndDt);
        System.out.println(clientName);
        System.out.println(memberID);
        System.out.println(modifierID);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityInfo _return = new com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityDetails> _returnMedicaidMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityDetails>();
            com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityDetails _returnMedicaidMemberEligibilityDetailsVal1 = new com.optum.rqns.services.medicaideligiblityTest.MedicaidMemberEligibilityDetails();
            _returnMedicaidMemberEligibilityDetailsVal1.setReturnCode(-1914534806);
            _returnMedicaidMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc1440254421");
            _returnMedicaidMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource1631311276");
            _returnMedicaidMemberEligibilityDetailsVal1.setMemberID("MemberID1039456866");
            _returnMedicaidMemberEligibilityDetailsVal1.setModifierID("ModifierID1416740288");
            _returnMedicaidMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID1207058632");
            _returnMedicaidMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber1050452412");
            _returnMedicaidMemberEligibilityDetailsVal1.setPlanDesc("PlanDesc-429470188");
            _returnMedicaidMemberEligibilityDetailsVal1.setLobID("LobID-2019503349");
            _returnMedicaidMemberEligibilityDetailsVal1.setLobIDDesc("LobIDDesc-548192597");
            _returnMedicaidMemberEligibilityDetailsVal1.setProgramTypeCd("ProgramTypeCd1125862577");
            _returnMedicaidMemberEligibilityDetailsVal1.setClassID("ClassID801467267");
            _returnMedicaidMemberEligibilityDetailsVal1.setClassIDDesc("ClassIDDesc-767811090");
            _returnMedicaidMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt-1676594097");
            _returnMedicaidMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt996942943");
            _returnMedicaidMemberEligibilityDetails.add(_returnMedicaidMemberEligibilityDetailsVal1);
            _return.getMedicaidMemberEligibilityDetails().addAll(_returnMedicaidMemberEligibilityDetails);
            _return.setErrorMsg("ErrorMsg1146745224");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
