
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.eligiblityTest;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-26T19:53:03.488+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "AcaMemberEligibilityService",
                      portName = "AcaMemberEligibilityServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/AcaMemberEligibilityService?wsdl",
                      endpointInterface = "com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityService")
                      
public class AcaMemberEligibilityServiceImpl implements AcaMemberEligibilityService {

    private static final Logger LOG = Logger.getLogger(AcaMemberEligibilityServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityService#getEligibleAcaMembersByMbrIDAndClient(java.lang.String  memberID ,)java.lang.String  modifierID ,)java.lang.String  clientName ,)java.lang.String  eligStrtDt ,)java.lang.String  eligEndDt ,)com.optum.rqns.services.eligiblityTest.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityInfo getEligibleAcaMembersByMbrIDAndClient(java.lang.String memberID,java.lang.String modifierID,java.lang.String clientName,java.lang.String eligStrtDt,java.lang.String eligEndDt,com.optum.rqns.services.eligiblityTest.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleAcaMembersByMbrIDAndClient");
        System.out.println(memberID);
        System.out.println(modifierID);
        System.out.println(clientName);
        System.out.println(eligStrtDt);
        System.out.println(eligEndDt);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityInfo _return = new com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityDetails> _returnAcaMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityDetails>();
            com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityDetails _returnAcaMemberEligibilityDetailsVal1 = new com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityDetails();
            _returnAcaMemberEligibilityDetailsVal1.setReturnCode(-1553357161);
            _returnAcaMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc-293291167");
            _returnAcaMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource915771495");
            _returnAcaMemberEligibilityDetailsVal1.setClientGuid("ClientGuid-1201715257");
            _returnAcaMemberEligibilityDetailsVal1.setMemberID("MemberID2011428218");
            _returnAcaMemberEligibilityDetailsVal1.setModifierID("ModifierID-19504653");
            _returnAcaMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID2094214008");
            _returnAcaMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber-971790525");
            _returnAcaMemberEligibilityDetailsVal1.setMetalLevel("MetalLevel1869680244");
            _returnAcaMemberEligibilityDetailsVal1.setSubscriberID("SubscriberID-1130971588");
            _returnAcaMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt1920812874");
            _returnAcaMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt-464383837");
            _returnAcaMemberEligibilityDetailsVal1.setEmpGroupID("EmpGroupID958657724");
            _returnAcaMemberEligibilityDetails.add(_returnAcaMemberEligibilityDetailsVal1);
            _return.getAcaMemberEligibilityDetails().addAll(_returnAcaMemberEligibilityDetails);
            _return.setErrorMsg("ErrorMsg-1858852180");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityService#getEligibleAcaMembersByGlbMbrIDAndClient(java.lang.String  globalMemberID ,)java.lang.String  clientName ,)java.lang.String  eligStrtDt ,)java.lang.String  eligEndDt ,)com.optum.rqns.services.eligiblityTest.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityInfo getEligibleAcaMembersByGlbMbrIDAndClient(java.lang.String globalMemberID,java.lang.String clientName,java.lang.String eligStrtDt,java.lang.String eligEndDt,com.optum.rqns.services.eligiblityTest.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleAcaMembersByGlbMbrIDAndClient");
        System.out.println(globalMemberID);
        System.out.println(clientName);
        System.out.println(eligStrtDt);
        System.out.println(eligEndDt);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityInfo _return = new com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityDetails> _returnAcaMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityDetails>();
            com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityDetails _returnAcaMemberEligibilityDetailsVal1 = new com.optum.rqns.services.eligiblityTest.AcaMemberEligibilityDetails();
            _returnAcaMemberEligibilityDetailsVal1.setReturnCode(-2081168706);
            _returnAcaMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc-1978435558");
            _returnAcaMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource833649362");
            _returnAcaMemberEligibilityDetailsVal1.setClientGuid("ClientGuid1828603529");
            _returnAcaMemberEligibilityDetailsVal1.setMemberID("MemberID1885129069");
            _returnAcaMemberEligibilityDetailsVal1.setModifierID("ModifierID-1027707846");
            _returnAcaMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID1768073136");
            _returnAcaMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber-94845677");
            _returnAcaMemberEligibilityDetailsVal1.setMetalLevel("MetalLevel-376431105");
            _returnAcaMemberEligibilityDetailsVal1.setSubscriberID("SubscriberID664105913");
            _returnAcaMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt1762310975");
            _returnAcaMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt891914984");
            _returnAcaMemberEligibilityDetailsVal1.setEmpGroupID("EmpGroupID-862800451");
            _returnAcaMemberEligibilityDetails.add(_returnAcaMemberEligibilityDetailsVal1);
            _return.getAcaMemberEligibilityDetails().addAll(_returnAcaMemberEligibilityDetails);
            _return.setErrorMsg("ErrorMsg-1635318921");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
