
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.rxClaimsLookup;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T14:59:54.648+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "RXClaimsLookUpService",
                      portName = "RXClaimsLookUpServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/rqns-services-web/services/RXClaimsLookUpService?wsdl",
                      endpointInterface = "com.optum.rqns.services.rxClaimsLookup.RXClaimsLookUpService")
                      
public class RXClaimsLookUpServiceImpl implements RXClaimsLookUpService {

    private static final Logger LOG = Logger.getLogger(RXClaimsLookUpServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.rxClaimsLookup.RXClaimsLookUpService#getRXClaimsByMbrIDAndClient(java.lang.String  memberIdentifier ,)java.lang.String  memberModifier ,)java.lang.String  clientGuid ,)com.optum.rqns.services.rxClaimsLookup.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.rxClaimsLookup.RxClaimsInfo getRXClaimsByMbrIDAndClient(java.lang.String memberIdentifier,java.lang.String memberModifier,java.lang.String clientGuid,com.optum.rqns.services.rxClaimsLookup.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getRXClaimsByMbrIDAndClient");
        System.out.println(memberIdentifier);
        System.out.println(memberModifier);
        System.out.println(clientGuid);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.rxClaimsLookup.RxClaimsInfo _return = new com.optum.rqns.services.rxClaimsLookup.RxClaimsInfo();
            _return.setReturnCode(Integer.valueOf(2096224065));
            _return.setReturnCodeDesc("ReturnCodeDesc-1429723846");
            java.util.List<com.optum.rqns.services.rxClaimsLookup.RxClaimDetails> _returnRxClaimDetails = new java.util.ArrayList<com.optum.rqns.services.rxClaimsLookup.RxClaimDetails>();
            com.optum.rqns.services.rxClaimsLookup.RxClaimDetails _returnRxClaimDetailsVal1 = new com.optum.rqns.services.rxClaimsLookup.RxClaimDetails();
            _returnRxClaimDetailsVal1.setMemberGlobalId("MemberGlobalId-1611882715");
            _returnRxClaimDetailsVal1.setMemberIdentifier("MemberIdentifier-1098323731");
            _returnRxClaimDetailsVal1.setMemberModifierId("MemberModifierId-1160689788");
            _returnRxClaimDetailsVal1.setNdcDesc("NdcDesc1899290450");
            _returnRxClaimDetailsVal1.setNdcCode("NdcCode2018560866");
            _returnRxClaimDetailsVal1.setDateFilled(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-08-07T14:59:54.668+05:30"));
            _returnRxClaimDetailsVal1.setQuantity("Quantity-239355405");
            _returnRxClaimDetailsVal1.setDateSupply("DateSupply-43814100");
            _returnRxClaimDetailsVal1.setProviderFirstName("ProviderFirstName1898457118");
            _returnRxClaimDetailsVal1.setProviderLastName("ProviderLastName452064696");
            _returnRxClaimDetailsVal1.setProviderMiddleName("ProviderMiddleName142999694");
            _returnRxClaimDetails.add(_returnRxClaimDetailsVal1);
            _return.getRxClaimDetails().addAll(_returnRxClaimDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
