
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.tinservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-25T16:49:48.773+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "providerTinService",
                      portName = "ProviderTinServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/rqns-services-web/services/providerTinService?wsdl",
                      endpointInterface = "com.optum.rqns.services.tinservice.ProviderTinService")
                      
public class ProviderTinServiceImpl implements ProviderTinService {

    private static final Logger LOG = Logger.getLogger(ProviderTinServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.tinservice.ProviderTinService#getProviderTinInfo(com.optum.rqns.services.tinservice.GetProviderTinInfo  getProviderTinInfo )*
     */
    public com.optum.rqns.services.tinservice.GetProviderTinInfoResponse getProviderTinInfo(GetProviderTinInfo getProviderTinInfo) throws ServiceException_Exception    { 
        LOG.info("Executing operation getProviderTinInfo");
        System.out.println(getProviderTinInfo);
        try {
            com.optum.rqns.services.tinservice.GetProviderTinInfoResponse _return = new com.optum.rqns.services.tinservice.GetProviderTinInfoResponse();
            com.optum.rqns.services.tinservice.ProviderTinInfo _returnProviderTinInfo = new com.optum.rqns.services.tinservice.ProviderTinInfo();
            _returnProviderTinInfo.setProviderNpiID("ProviderNpiID1101201228");
            _returnProviderTinInfo.setProviderTin("ProviderTin372100861");
            _returnProviderTinInfo.setProviderTinName("ProviderTinName1149854759");
            _returnProviderTinInfo.setDataSource("DataSource444198572");
            _returnProviderTinInfo.setReturnCode(209178053);
            _returnProviderTinInfo.setReturnCodeDesc("ReturnCodeDesc1133684148");
            _return.setProviderTinInfo(_returnProviderTinInfo);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
