package com.optum.rqns.services.hicTest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The service name for HicHistoryService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-26T19:47:22.832+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "hicHistoryService", 
                  wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/hicHistoryService?wsdl",
                  targetNamespace = "http://services.rqns.optum.com/") 
public class HicHistoryService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.rqns.optum.com/", "hicHistoryService");
    public final static QName HicHistoryServiceImplPort = new QName("http://services.rqns.optum.com/", "HicHistoryServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/hicHistoryService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HicHistoryService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/hicHistoryService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HicHistoryService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HicHistoryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HicHistoryService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HicHistoryService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HicHistoryService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HicHistoryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * The service port for HicHistoryService
     *
     * @return
     *     returns HicHistoryService
     */
    @WebEndpoint(name = "HicHistoryServiceImplPort")
    public HicHistoryService getHicHistoryServiceImplPort() {
        return super.getPort(HicHistoryServiceImplPort, HicHistoryService.class);
    }

    /**
     * The service port for HicHistoryService
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HicHistoryService
     */
    @WebEndpoint(name = "HicHistoryServiceImplPort")
    public HicHistoryService getHicHistoryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HicHistoryServiceImplPort, HicHistoryService.class, features);
    }

}
