
package com.optum.rqns.services.medicareEligiblity;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;

import javax.xml.namespace.QName;

import com.optum.rqns.services.medicareEligiblity.MemberEligibilityService;
import com.optum.rqns.services.medicareEligiblity.MemberEligibilityService_Service;
import com.optum.rqns.services.medicareEligiblity.ServiceException_Exception;
import com.optum.rqns.services.utils.DataBaseConnect;
import com.optum.rqns.services.utils.Utility;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T13:21:11.918+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class MemberEligibilityService_MemberEligibilityServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "memberEligibilityService");

    private MemberEligibilityService_MemberEligibilityServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
    	System.setProperty("javax.net.ssl.keyStore","C:/CRQS/Webservices/Soap/Stage/rqns_stg.jks");
        System.setProperty("javax.net.ssl.keyStorePassword","changeit");
        System.setProperty("javax.net.ssl.trustStore","C:/CRQS/Webservices/Soap/Stage/cpc_client_truststore.jks");
        System.setProperty("javax.net.ssl.trustStorePassword","changeit");
        String hic="";
        String sStrtDt="";
        String sEndDt="";
        URL wsdlURL = MemberEligibilityService_Service.WSDL_LOCATION;
       
      
        MemberEligibilityService_Service ss = new MemberEligibilityService_Service(wsdlURL, SERVICE_NAME);
        MemberEligibilityService port = ss.getMemberEligibilityServiceImplPort();  
        
        {
        	//select * from  cms_mmr_rstd_elig_sts order by updt_dttm desc
        String sRequest="select hic_nbr,pay_adj_strt_dt,pay_adj_end_dt,contr_nbr,sub_plan_id,sys_cd,par_clnt_guid from  cms_mmr_rstd_elig_sts order by updt_dttm desc";
        System.out.println("Invoking getEligibleMembers...");
        System.out.println(sRequest);
        ResultSet rs=DataBaseConnect.getRsList("STAGE", sRequest);
        int iCount=0;
        while (rs.next()){
        	hic=rs.getString(1);
        	sStrtDt=rs.getString(2);
        	sEndDt=rs.getString(3);
        	break;
        }
        
        com.optum.rqns.services.medicareEligiblity.GetEligibleMembers _getEligibleMembers_getEligibleMembers = new com.optum.rqns.services.medicareEligiblity.GetEligibleMembers();
        _getEligibleMembers_getEligibleMembers.setMemberHIC(hic);
        _getEligibleMembers_getEligibleMembers.setRangeStrtDt(Utility.formatDateForService(sStrtDt));
        _getEligibleMembers_getEligibleMembers.setRangeEndDt(Utility.formatDateForService(sEndDt));
        com.optum.rqns.services.medicareEligiblity.ServiceMetaData _getEligibleMembers_getEligibleMembersMetaData = new com.optum.rqns.services.medicareEligiblity.ServiceMetaData();
        _getEligibleMembers_getEligibleMembersMetaData.setAppId("9032afa9f3e34e6fd0e05e967be021f7");
        _getEligibleMembers_getEligibleMembers.setMetaData(_getEligibleMembers_getEligibleMembersMetaData);
        try {
        	com.optum.rqns.services.medicareEligiblity.GetEligibleMembersResponse _getEligibleMembers__return = port.getEligibleMembers(_getEligibleMembers_getEligibleMembers);
            System.out.println("getEligibleMembers.result=" + _getEligibleMembers__return);
            System.out.println("response");
            //System.out.println(_getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.getMemberHicHistory().);
            System.out.println(_getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0).hicNumber);
           // _getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0);
            System.out.println(_getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0).eligibilitySource);
            System.out.println(_getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0).enrlStrtDt);
            System.out.println(_getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0).enrlEndDt);
            System.out.println(_getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0).subPlnId);
            System.out.println(_getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0).parClntGuid);
            
        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
