
package com.optum.rqns.services.medicareEigiblityTest;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;

import javax.xml.namespace.QName;

import com.optum.rqns.services.utils.DataBaseConnect;
import com.optum.rqns.services.utils.Utility;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T13:20:12.543+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class MemberEligibilityService_MemberEligibilityServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "memberEligibilityService");

    public MemberEligibilityService_MemberEligibilityServiceImplPort_Client() {
    }

    public  String medicareMeberEligiblity() throws java.lang.Exception {
    	String sReturn="";
        String hic="";
        String sStrtDt="";
        String sEndDt="";
        String scontrNbr="";
    	String subplnId="";
    	String sSysCode="";
    	String sPrntGuid="";
    	com.optum.rqns.services.medicareEigiblityTest.GetEligibleMembersResponse _getEligibleMembers__return;
        URL wsdlURL = MemberEligibilityService_Service.WSDL_LOCATION;
       
      
        MemberEligibilityService_Service ss = new MemberEligibilityService_Service(wsdlURL, SERVICE_NAME);
        MemberEligibilityService port = ss.getMemberEligibilityServiceImplPort();  
        
        {
        	//select * from  cms_mmr_rstd_elig_sts order by updt_dttm desc
        String sRequest="select hic_nbr,pay_adj_strt_dt,pay_adj_end_dt,contr_nbr,sub_plan_id,sys_cd,par_clnt_guid from  cms_mmr_rstd_elig_sts st, vw_cs_clnt_guid_mod vw where vw.clnt_guid=st.par_clnt_guid and vw.ins_catg_cd='MR'";
        System.out.println("Invoking getEligibleMembers...");
        System.out.println(sRequest);
        ResultSet rs=DataBaseConnect.getRsList("TEST", sRequest);
        int iCount=0;
        while (rs.next()){
        	hic=rs.getString(1);
        	sStrtDt=rs.getString(2);
        	sEndDt=rs.getString(3);
        	scontrNbr=rs.getString(4);
        	subplnId=rs.getString(5);
        	sSysCode=rs.getString(6);
        	sPrntGuid=rs.getString(7);
        	break;
        }
        
        com.optum.rqns.services.medicareEigiblityTest.GetEligibleMembers _getEligibleMembers_getEligibleMembers = new com.optum.rqns.services.medicareEigiblityTest.GetEligibleMembers();
        _getEligibleMembers_getEligibleMembers.setMemberHIC(hic);
        _getEligibleMembers_getEligibleMembers.setRangeStrtDt(Utility.formatDateForService(sStrtDt));
        _getEligibleMembers_getEligibleMembers.setRangeEndDt(Utility.formatDateForService(sEndDt));
        com.optum.rqns.services.medicareEigiblityTest.ServiceMetaData _getEligibleMembers_getEligibleMembersMetaData = new com.optum.rqns.services.medicareEigiblityTest.ServiceMetaData();
        _getEligibleMembers_getEligibleMembersMetaData.setAppId("9032afa9f3e34e6fd0e05e967be021f7");
        _getEligibleMembers_getEligibleMembers.setMetaData(_getEligibleMembers_getEligibleMembersMetaData);
        try {
             _getEligibleMembers__return = port.getEligibleMembers(_getEligibleMembers_getEligibleMembers);
            System.out.println("getEligibleMembers.result=" + _getEligibleMembers__return);
            System.out.println("response");
            //System.out.println(_getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.getMemberHicHistory().);
            MemberHicHistory oRecord = _getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0);
         //   _getEligibleMembers__return.memberEligibilityInfo.memberHicHistoryList.memberHicHistory.get(0).
            
            if (Utility.formatDateForService(sStrtDt).equals(oRecord.enrlStrtDt) &&
            		Utility.formatDateForService(sEndDt).equals(oRecord.enrlEndDt) &&
            		hic.equals(oRecord.hicNumber) &&
            		scontrNbr.equals(oRecord.contrNbr) &&
            		subplnId.equals(oRecord.subPlnId) &&
            		sPrntGuid.equals(oRecord.parClntGuid))
      
					{
						
			
            	sReturn="getEligibleMcaidMembersByHic  --------Passed:-------";
            	
            	 sReturn=sReturn+" ************************Request******************************************";
            	sReturn=sReturn+ " Hic number- " + hic;
            	sReturn=sReturn+ " Start date:- " +sStrtDt;
            	sReturn=sReturn+ " End Date:- " +sEndDt;
            	
            	
            
            	
            	sReturn=sReturn+"************************Response******************************************";
            	sReturn=sReturn+ " Hic number- " + oRecord.hicNumber;
            	sReturn=sReturn+ " Start date:- " +oRecord.enrlStrtDt;
            	sReturn=sReturn+ " End Date:- " +oRecord.enrlEndDt;
            	sReturn=sReturn+ " Contract Number- " + oRecord.contrNbr;
            	sReturn=sReturn+ "Source:- " +oRecord.eligibilitySource;
            	sReturn=sReturn+ " Parent GUID:- " +oRecord.parClntGuid;
            
            	
            }
            else
            {
            	sReturn="getEligibleMcaidMembersByHic  --------Failed:-------";
            	
           	 sReturn=sReturn+" ************************Request******************************************";
         	sReturn=sReturn+ " Hic number- " + hic;
         	sReturn=sReturn+ " Start date:- " +sStrtDt;
         	sReturn=sReturn+ " End Date:- " +sEndDt;
         	
         	
         
         	
         	sReturn=sReturn+"************************Response******************************************";
         	sReturn=sReturn+ " Hic number- " + oRecord.hicNumber;
         	sReturn=sReturn+ " Start date:- " +oRecord.enrlStrtDt;
         	sReturn=sReturn+ " End Date:- " +oRecord.enrlEndDt;
         	sReturn=sReturn+ " Contract Number- " + oRecord.contrNbr;
         	sReturn=sReturn+ "Source:- " +oRecord.eligibilitySource;
         	sReturn=sReturn+ " Parent GUID:- " +oRecord.parClntGuid;
         
            }

        } 
         catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
            sReturn="Service failed msg:" + e.getMessage()+ " with request  "+ hic+"----" + "start date "+ Utility.formatDateForService(sStrtDt) + "--------end date  " +Utility.formatDateForService(sEndDt);
        }
        
        catch (Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
            sReturn="Service failed msg:" + e.getMessage()+ " with request  "+ hic+"----" + "start date "+ Utility.formatDateForService(sStrtDt) + "--------end date  " +Utility.formatDateForService(sEndDt);
        }
            }
		return sReturn;

      //  System.exit(0);
    }

}
