package com.optum.rqns.services.medicareEigiblityTest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The service name for MemberEligibilityService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T13:20:12.697+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "memberEligibilityService", 
                  wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/memberEligibilityService?wsdl",
                  targetNamespace = "http://services.rqns.optum.com/") 
public class MemberEligibilityService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.rqns.optum.com/", "memberEligibilityService");
    public final static QName MemberEligibilityServiceImplPort = new QName("http://services.rqns.optum.com/", "MemberEligibilityServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/memberEligibilityService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MemberEligibilityService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/memberEligibilityService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MemberEligibilityService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MemberEligibilityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberEligibilityService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MemberEligibilityService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MemberEligibilityService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MemberEligibilityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * The service port for MemberEligibilityService
     *
     * @return
     *     returns MemberEligibilityService
     */
    @WebEndpoint(name = "MemberEligibilityServiceImplPort")
    public MemberEligibilityService getMemberEligibilityServiceImplPort() {
        return super.getPort(MemberEligibilityServiceImplPort, MemberEligibilityService.class);
    }

    /**
     * The service port for MemberEligibilityService
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberEligibilityService
     */
    @WebEndpoint(name = "MemberEligibilityServiceImplPort")
    public MemberEligibilityService getMemberEligibilityServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MemberEligibilityServiceImplPort, MemberEligibilityService.class, features);
    }

}
