
package com.optum.rqns.services.npiLookup;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.optum.rqns.services.utils.DataBaseConnect;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T15:06:14.918+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class ProviderNpiLookUpService_ProviderNpiLookUpServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "providerNpiLookUpService");

    private ProviderNpiLookUpService_ProviderNpiLookUpServiceImplPort_Client() {
    }

    public  String npiLookup() throws java.lang.Exception {
    	
    	String sProvGlbId="";
    	String sClntGuid="";
    	String sProvId="";
        String sProvModId="";
        String sSubCliSk="";
        String sCliNm="";
        
        URL wsdlURL = ProviderNpiLookUpService_Service.WSDL_LOCATION;
      
      String sRequest="select prov_glb_id,clnt_guid,prov_enty_id,prov_enty_mod_id,sub_cli_sk from cs_prov_glb_id where clnt_guid is  not null and prov_glb_id is not null ";
      
      System.out.println(sRequest);
      ResultSet rs=DataBaseConnect.getRsList("STAGE", sRequest);
      //int iCount=0;
      while (rs.next()){
      	sProvGlbId=rs.getString(1);
      	sClntGuid=rs.getString(2);
      	sProvId=rs.getString(3);
      	sProvModId=rs.getString(4);
      	sSubCliSk=rs.getString(5);
      	break;
      }
      String sRequest1="select src_sys_nm,sub_src_sys_nm,sub_cli_org_nm from vw_cs_clnt_guid_mod where clnt_guid='" + sClntGuid +"' and cli_modifier="+sProvModId+" and src_Sys_cd='RADC_PRV'";
      System.out.println(sRequest1);
      ResultSet rs1=DataBaseConnect.getRsList("STAGE", sRequest1);
     // int iCount1=0;
      while (rs1.next()){
      
      	sCliNm=rs1.getString(3);
      	break;
      }
      ProviderNpiLookUpService_Service ss = new ProviderNpiLookUpService_Service(wsdlURL, SERVICE_NAME);
        ProviderNpiLookUpService port = ss.getProviderNpiLookUpServiceImplPort();  
        
        {
        	
        System.out.println("Invoking getClientP360ProviderInfoByGlobalID...");
        System.out.println(sProvGlbId);
        System.out.println(sCliNm);
        com.optum.rqns.services.npiLookup.ServiceMetaData _getClientP360ProviderInfoByGlobalID_metaData = new com.optum.rqns.services.npiLookup.ServiceMetaData();
        _getClientP360ProviderInfoByGlobalID_metaData.setAppId("9032afa9f3e34e6fd0e05e967be021f7");
        java.lang.String _getClientP360ProviderInfoByGlobalID_globalProviderID = sProvGlbId;
        java.lang.String _getClientP360ProviderInfoByGlobalID_clientName = sCliNm;
        try {
            com.optum.rqns.services.npiLookup.ProviderDemographicInfo _getClientP360ProviderInfoByGlobalID__return = port.getClientP360ProviderInfoByGlobalID(_getClientP360ProviderInfoByGlobalID_metaData, _getClientP360ProviderInfoByGlobalID_globalProviderID, _getClientP360ProviderInfoByGlobalID_clientName);
            System.out.println("getClientP360ProviderInfoByGlobalID.result=" + _getClientP360ProviderInfoByGlobalID__return);
            System.out.println(_getClientP360ProviderInfoByGlobalID__return.providerDemographicDetails.get(0).clientGuid);
        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }/* 
        {
        System.out.println("Invoking getNppesProviderInfoByNpi...");
        com.optum.rqns.services.npiLookup.ServiceMetaData _getNppesProviderInfoByNpi_metaData = new com.optum.rqns.services.npiLookup.ServiceMetaData();
        _getNppesProviderInfoByNpi_metaData.setAppId("AppId-792420629");
        java.lang.Long _getNppesProviderInfoByNpi_providerNpiID = Long.valueOf(-6251865382169800192l);
        try {
            com.optum.rqns.services.npiLookup.ProviderInfo _getNppesProviderInfoByNpi__return = port.getNppesProviderInfoByNpi(_getNppesProviderInfoByNpi_metaData, _getNppesProviderInfoByNpi_providerNpiID);
            System.out.println("getNppesProviderInfoByNpi.result=" + _getNppesProviderInfoByNpi__return);
            

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
           }
        {
        System.out.println("Invoking getClientProviderInfoByProviderIDAndClientName...");
        com.optum.rqns.services.npiLookup.ServiceMetaData _getClientProviderInfoByProviderIDAndClientName_metaData = new com.optum.rqns.services.npiLookup.ServiceMetaData();
        _getClientProviderInfoByProviderIDAndClientName_metaData.setAppId("AppId1186566336");
        java.lang.String _getClientProviderInfoByProviderIDAndClientName_healthPlanProviderID = "_getClientProviderInfoByProviderIDAndClientName_healthPlanProviderID-1038663732";
        java.lang.String _getClientProviderInfoByProviderIDAndClientName_modifierID = "_getClientProviderInfoByProviderIDAndClientName_modifierID-536615444";
        java.lang.String _getClientProviderInfoByProviderIDAndClientName_clientName = "_getClientProviderInfoByProviderIDAndClientName_clientName993144918";
        try {
            com.optum.rqns.services.npiLookup.ProviderDemographicInfo _getClientProviderInfoByProviderIDAndClientName__return = port.getClientProviderInfoByProviderIDAndClientName(_getClientProviderInfoByProviderIDAndClientName_metaData, _getClientProviderInfoByProviderIDAndClientName_healthPlanProviderID, _getClientProviderInfoByProviderIDAndClientName_modifierID, _getClientProviderInfoByProviderIDAndClientName_clientName);
            System.out.println("getClientProviderInfoByProviderIDAndClientName.result=" + _getClientProviderInfoByProviderIDAndClientName__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getClientProviderInfoByNpiAndClientName...");
        com.optum.rqns.services.npiLookup.ServiceMetaData _getClientProviderInfoByNpiAndClientName_metaData = new com.optum.rqns.services.npiLookup.ServiceMetaData();
        _getClientProviderInfoByNpiAndClientName_metaData.setAppId("AppId-709336227");
        java.lang.String _getClientProviderInfoByNpiAndClientName_providerNpiId = "_getClientProviderInfoByNpiAndClientName_providerNpiId-1656079833";
        java.lang.String _getClientProviderInfoByNpiAndClientName_clientName = "_getClientProviderInfoByNpiAndClientName_clientName-1288439759";
        try {
            com.optum.rqns.services.npiLookup.ProviderDemographicInfo _getClientProviderInfoByNpiAndClientName__return = port.getClientProviderInfoByNpiAndClientName(_getClientProviderInfoByNpiAndClientName_metaData, _getClientProviderInfoByNpiAndClientName_providerNpiId, _getClientProviderInfoByNpiAndClientName_clientName);
            System.out.println("getClientProviderInfoByNpiAndClientName.result=" + _getClientProviderInfoByNpiAndClientName__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }*/

    //    System.exit(0);
		return sRequest1;
    }

}
