
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.npiLookup;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T15:06:15.031+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "providerNpiLookUpService",
                      portName = "ProviderNpiLookUpServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/rqns-services-web/services/providerNpiLookUpService?wsdl",
                      endpointInterface = "com.optum.rqns.services.npiLookup.ProviderNpiLookUpService")
                      
public class ProviderNpiLookUpServiceImpl implements ProviderNpiLookUpService {

    private static final Logger LOG = Logger.getLogger(ProviderNpiLookUpServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.npiLookup.ProviderNpiLookUpService#getClientP360ProviderInfoByGlobalID(com.optum.rqns.services.npiLookup.ServiceMetaData  metaData ,)java.lang.String  globalProviderID ,)java.lang.String  clientName )*
     */
    public com.optum.rqns.services.npiLookup.ProviderDemographicInfo getClientP360ProviderInfoByGlobalID(com.optum.rqns.services.npiLookup.ServiceMetaData metaData,java.lang.String globalProviderID,java.lang.String clientName) throws ServiceException_Exception    { 
        LOG.info("Executing operation getClientP360ProviderInfoByGlobalID");
        System.out.println(metaData);
        System.out.println(globalProviderID);
        System.out.println(clientName);
        try {
            com.optum.rqns.services.npiLookup.ProviderDemographicInfo _return = new com.optum.rqns.services.npiLookup.ProviderDemographicInfo();
            _return.setReturnCode(Integer.valueOf(959007348));
            _return.setReturnCodeDesc("ReturnCodeDesc-85111184");
            java.util.List<com.optum.rqns.services.npiLookup.ProviderDemographicDetails> _returnProviderDemographicDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderDemographicDetails>();
            com.optum.rqns.services.npiLookup.ProviderDemographicDetails _returnProviderDemographicDetailsVal1 = new com.optum.rqns.services.npiLookup.ProviderDemographicDetails();
            _returnProviderDemographicDetailsVal1.setDataSource("DataSource-131959056");
            _returnProviderDemographicDetailsVal1.setClientGuid("ClientGuid1496020738");
            _returnProviderDemographicDetailsVal1.setProviderID("ProviderID1592189700");
            _returnProviderDemographicDetailsVal1.setGlobalProviderID("GlobalProviderID1046861212");
            _returnProviderDemographicDetailsVal1.setProviderModifier("ProviderModifier-1579693206");
            _returnProviderDemographicDetailsVal1.setProviderFullName("ProviderFullName1324308253");
            _returnProviderDemographicDetailsVal1.setPhysicianLastName("PhysicianLastName-703752568");
            _returnProviderDemographicDetailsVal1.setProviderFirstName("ProviderFirstName-87341318");
            _returnProviderDemographicDetailsVal1.setProviderMiddleName("ProviderMiddleName44885247");
            _returnProviderDemographicDetailsVal1.setPhysicianNameSuffix("PhysicianNameSuffix-919925602");
            _returnProviderDemographicDetailsVal1.setProviderEntityCapitationInd("ProviderEntityCapitationInd958143814");
            _returnProviderDemographicDetailsVal1.setParticipatingStatus("ParticipatingStatus-22886409");
            _returnProviderDemographicDetailsVal1.setProviderContractStartDate("ProviderContractStartDate-369516977");
            _returnProviderDemographicDetailsVal1.setProviderContractEndDate("ProviderContractEndDate2104933502");
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderNPI = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderNPI().addAll(_returnProviderDemographicDetailsVal1ProviderNPI);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderTIN = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderTIN().addAll(_returnProviderDemographicDetailsVal1ProviderTIN);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1SpecialtyCode = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getSpecialtyCode().addAll(_returnProviderDemographicDetailsVal1SpecialtyCode);
            com.optum.rqns.services.npiLookup.ProviderAffiliationInfo _returnProviderDemographicDetailsVal1ProviderAffiliationInfo = new com.optum.rqns.services.npiLookup.ProviderAffiliationInfo();
            java.util.List<com.optum.rqns.services.npiLookup.ProviderAffiliationDetails> _returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderAffiliationDetails>();
            _returnProviderDemographicDetailsVal1ProviderAffiliationInfo.getProviderAffiliationDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails);
            _returnProviderDemographicDetailsVal1.setProviderAffiliationInfo(_returnProviderDemographicDetailsVal1ProviderAffiliationInfo);
            com.optum.rqns.services.npiLookup.ProviderAddressInfo _returnProviderDemographicDetailsVal1ProviderAddressInfo = new com.optum.rqns.services.npiLookup.ProviderAddressInfo();
            java.util.List<com.optum.rqns.services.npiLookup.ProviderAddressDetails> _returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderAddressDetails>();
            _returnProviderDemographicDetailsVal1ProviderAddressInfo.getProviderAddressDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails);
            _returnProviderDemographicDetailsVal1.setProviderAddressInfo(_returnProviderDemographicDetailsVal1ProviderAddressInfo);
            _returnProviderDemographicDetails.add(_returnProviderDemographicDetailsVal1);
            _return.getProviderDemographicDetails().addAll(_returnProviderDemographicDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.npiLookup.ProviderNpiLookUpService#getNppesProviderInfoByNpi(com.optum.rqns.services.npiLookup.ServiceMetaData  metaData ,)java.lang.Long  providerNpiID )*
     */
    public com.optum.rqns.services.npiLookup.ProviderInfo getNppesProviderInfoByNpi(com.optum.rqns.services.npiLookup.ServiceMetaData metaData,java.lang.Long providerNpiID) throws ServiceException_Exception    { 
        LOG.info("Executing operation getNppesProviderInfoByNpi");
        System.out.println(metaData);
        System.out.println(providerNpiID);
        try {
            com.optum.rqns.services.npiLookup.ProviderInfo _return = new com.optum.rqns.services.npiLookup.ProviderInfo();
            _return.setReturnCode(Integer.valueOf(1954347136));
            _return.setReturnCodeDesc("ReturnCodeDesc965135483");
            java.util.List<com.optum.rqns.services.npiLookup.ProviderDetails> _returnProviderDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderDetails>();
            com.optum.rqns.services.npiLookup.ProviderDetails _returnProviderDetailsVal1 = new com.optum.rqns.services.npiLookup.ProviderDetails();
            _returnProviderDetailsVal1.setDataSource("DataSource-35843702");
            _returnProviderDetailsVal1.setProviderNPI(-1508562541460635928l);
            _returnProviderDetailsVal1.setProvOrgName("ProvOrgName-966894514");
            _returnProviderDetailsVal1.setProvLastName("ProvLastName1833827330");
            _returnProviderDetailsVal1.setProvFirstName("ProvFirstName163434112");
            _returnProviderDetailsVal1.setProvMiddleName("ProvMiddleName1490762834");
            _returnProviderDetailsVal1.setProvEnumDate("ProvEnumDate-2064069961");
            _returnProviderDetailsVal1.setLastUpdateDate("LastUpdateDate-1047181573");
            _returnProviderDetailsVal1.setNpiDeactDate("NpiDeactDate-1923735525");
            _returnProviderDetailsVal1.setNpiReactDate("NpiReactDate1241307307");
            _returnProviderDetailsVal1.setProvAddrTypeCode("ProvAddrTypeCode-491076507");
            _returnProviderDetailsVal1.setProvAddrLine1("ProvAddrLine11353173445");
            _returnProviderDetailsVal1.setProvAddrLine2("ProvAddrLine22093522899");
            _returnProviderDetailsVal1.setProvCity("ProvCity-138872279");
            _returnProviderDetailsVal1.setProvState("ProvState-982263917");
            _returnProviderDetailsVal1.setProvZip("ProvZip-879650548");
            java.util.List<java.lang.String> _returnProviderDetailsVal1ProvSpecialtyCode = new java.util.ArrayList<java.lang.String>();
            _returnProviderDetailsVal1.getProvSpecialtyCode().addAll(_returnProviderDetailsVal1ProvSpecialtyCode);
            java.util.List<java.lang.String> _returnProviderDetailsVal1ProvOtherID = new java.util.ArrayList<java.lang.String>();
            _returnProviderDetailsVal1.getProvOtherID().addAll(_returnProviderDetailsVal1ProvOtherID);
            _returnProviderDetails.add(_returnProviderDetailsVal1);
            _return.getProviderDetails().addAll(_returnProviderDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.npiLookup.ProviderNpiLookUpService#getClientProviderInfoByProviderIDAndClientName(com.optum.rqns.services.npiLookup.ServiceMetaData  metaData ,)java.lang.String  healthPlanProviderID ,)java.lang.String  modifierID ,)java.lang.String  clientName )*
     */
    public com.optum.rqns.services.npiLookup.ProviderDemographicInfo getClientProviderInfoByProviderIDAndClientName(com.optum.rqns.services.npiLookup.ServiceMetaData metaData,java.lang.String healthPlanProviderID,java.lang.String modifierID,java.lang.String clientName) throws ServiceException_Exception    { 
        LOG.info("Executing operation getClientProviderInfoByProviderIDAndClientName");
        System.out.println(metaData);
        System.out.println(healthPlanProviderID);
        System.out.println(modifierID);
        System.out.println(clientName);
        try {
            com.optum.rqns.services.npiLookup.ProviderDemographicInfo _return = new com.optum.rqns.services.npiLookup.ProviderDemographicInfo();
            _return.setReturnCode(Integer.valueOf(948067967));
            _return.setReturnCodeDesc("ReturnCodeDesc-461220157");
            java.util.List<com.optum.rqns.services.npiLookup.ProviderDemographicDetails> _returnProviderDemographicDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderDemographicDetails>();
            com.optum.rqns.services.npiLookup.ProviderDemographicDetails _returnProviderDemographicDetailsVal1 = new com.optum.rqns.services.npiLookup.ProviderDemographicDetails();
            _returnProviderDemographicDetailsVal1.setDataSource("DataSource-2092836250");
            _returnProviderDemographicDetailsVal1.setClientGuid("ClientGuid880179054");
            _returnProviderDemographicDetailsVal1.setProviderID("ProviderID-1103938513");
            _returnProviderDemographicDetailsVal1.setGlobalProviderID("GlobalProviderID-1648006941");
            _returnProviderDemographicDetailsVal1.setProviderModifier("ProviderModifier-791030887");
            _returnProviderDemographicDetailsVal1.setProviderFullName("ProviderFullName-2083505330");
            _returnProviderDemographicDetailsVal1.setPhysicianLastName("PhysicianLastName-884229266");
            _returnProviderDemographicDetailsVal1.setProviderFirstName("ProviderFirstName838499162");
            _returnProviderDemographicDetailsVal1.setProviderMiddleName("ProviderMiddleName-622573221");
            _returnProviderDemographicDetailsVal1.setPhysicianNameSuffix("PhysicianNameSuffix-707969561");
            _returnProviderDemographicDetailsVal1.setProviderEntityCapitationInd("ProviderEntityCapitationInd-999406390");
            _returnProviderDemographicDetailsVal1.setParticipatingStatus("ParticipatingStatus876085396");
            _returnProviderDemographicDetailsVal1.setProviderContractStartDate("ProviderContractStartDate-1047192969");
            _returnProviderDemographicDetailsVal1.setProviderContractEndDate("ProviderContractEndDate-599906396");
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderNPI = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderNPI().addAll(_returnProviderDemographicDetailsVal1ProviderNPI);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderTIN = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderTIN().addAll(_returnProviderDemographicDetailsVal1ProviderTIN);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1SpecialtyCode = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getSpecialtyCode().addAll(_returnProviderDemographicDetailsVal1SpecialtyCode);
            com.optum.rqns.services.npiLookup.ProviderAffiliationInfo _returnProviderDemographicDetailsVal1ProviderAffiliationInfo = new com.optum.rqns.services.npiLookup.ProviderAffiliationInfo();
            java.util.List<com.optum.rqns.services.npiLookup.ProviderAffiliationDetails> _returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderAffiliationDetails>();
            _returnProviderDemographicDetailsVal1ProviderAffiliationInfo.getProviderAffiliationDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails);
            _returnProviderDemographicDetailsVal1.setProviderAffiliationInfo(_returnProviderDemographicDetailsVal1ProviderAffiliationInfo);
            com.optum.rqns.services.npiLookup.ProviderAddressInfo _returnProviderDemographicDetailsVal1ProviderAddressInfo = new com.optum.rqns.services.npiLookup.ProviderAddressInfo();
            java.util.List<com.optum.rqns.services.npiLookup.ProviderAddressDetails> _returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderAddressDetails>();
            _returnProviderDemographicDetailsVal1ProviderAddressInfo.getProviderAddressDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails);
            _returnProviderDemographicDetailsVal1.setProviderAddressInfo(_returnProviderDemographicDetailsVal1ProviderAddressInfo);
            _returnProviderDemographicDetails.add(_returnProviderDemographicDetailsVal1);
            _return.getProviderDemographicDetails().addAll(_returnProviderDemographicDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.npiLookup.ProviderNpiLookUpService#getClientProviderInfoByNpiAndClientName(com.optum.rqns.services.npiLookup.ServiceMetaData  metaData ,)java.lang.String  providerNpiId ,)java.lang.String  clientName )*
     */
    public com.optum.rqns.services.npiLookup.ProviderDemographicInfo getClientProviderInfoByNpiAndClientName(com.optum.rqns.services.npiLookup.ServiceMetaData metaData,java.lang.String providerNpiId,java.lang.String clientName) throws ServiceException_Exception    { 
        LOG.info("Executing operation getClientProviderInfoByNpiAndClientName");
        System.out.println(metaData);
        System.out.println(providerNpiId);
        System.out.println(clientName);
        try {
            com.optum.rqns.services.npiLookup.ProviderDemographicInfo _return = new com.optum.rqns.services.npiLookup.ProviderDemographicInfo();
            _return.setReturnCode(Integer.valueOf(313695892));
            _return.setReturnCodeDesc("ReturnCodeDesc1882630412");
            java.util.List<com.optum.rqns.services.npiLookup.ProviderDemographicDetails> _returnProviderDemographicDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderDemographicDetails>();
            com.optum.rqns.services.npiLookup.ProviderDemographicDetails _returnProviderDemographicDetailsVal1 = new com.optum.rqns.services.npiLookup.ProviderDemographicDetails();
            _returnProviderDemographicDetailsVal1.setDataSource("DataSource897926581");
            _returnProviderDemographicDetailsVal1.setClientGuid("ClientGuid-660361811");
            _returnProviderDemographicDetailsVal1.setProviderID("ProviderID272800995");
            _returnProviderDemographicDetailsVal1.setGlobalProviderID("GlobalProviderID719056129");
            _returnProviderDemographicDetailsVal1.setProviderModifier("ProviderModifier1951875968");
            _returnProviderDemographicDetailsVal1.setProviderFullName("ProviderFullName-1310583611");
            _returnProviderDemographicDetailsVal1.setPhysicianLastName("PhysicianLastName12799455");
            _returnProviderDemographicDetailsVal1.setProviderFirstName("ProviderFirstName729218409");
            _returnProviderDemographicDetailsVal1.setProviderMiddleName("ProviderMiddleName-1324034616");
            _returnProviderDemographicDetailsVal1.setPhysicianNameSuffix("PhysicianNameSuffix187272530");
            _returnProviderDemographicDetailsVal1.setProviderEntityCapitationInd("ProviderEntityCapitationInd-814864837");
            _returnProviderDemographicDetailsVal1.setParticipatingStatus("ParticipatingStatus-869838810");
            _returnProviderDemographicDetailsVal1.setProviderContractStartDate("ProviderContractStartDate-1983942103");
            _returnProviderDemographicDetailsVal1.setProviderContractEndDate("ProviderContractEndDate587185341");
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderNPI = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderNPI().addAll(_returnProviderDemographicDetailsVal1ProviderNPI);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderTIN = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderTIN().addAll(_returnProviderDemographicDetailsVal1ProviderTIN);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1SpecialtyCode = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getSpecialtyCode().addAll(_returnProviderDemographicDetailsVal1SpecialtyCode);
            com.optum.rqns.services.npiLookup.ProviderAffiliationInfo _returnProviderDemographicDetailsVal1ProviderAffiliationInfo = new com.optum.rqns.services.npiLookup.ProviderAffiliationInfo();
            java.util.List<com.optum.rqns.services.npiLookup.ProviderAffiliationDetails> _returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderAffiliationDetails>();
            _returnProviderDemographicDetailsVal1ProviderAffiliationInfo.getProviderAffiliationDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails);
            _returnProviderDemographicDetailsVal1.setProviderAffiliationInfo(_returnProviderDemographicDetailsVal1ProviderAffiliationInfo);
            com.optum.rqns.services.npiLookup.ProviderAddressInfo _returnProviderDemographicDetailsVal1ProviderAddressInfo = new com.optum.rqns.services.npiLookup.ProviderAddressInfo();
            java.util.List<com.optum.rqns.services.npiLookup.ProviderAddressDetails> _returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookup.ProviderAddressDetails>();
            _returnProviderDemographicDetailsVal1ProviderAddressInfo.getProviderAddressDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails);
            _returnProviderDemographicDetailsVal1.setProviderAddressInfo(_returnProviderDemographicDetailsVal1ProviderAddressInfo);
            _returnProviderDemographicDetails.add(_returnProviderDemographicDetailsVal1);
            _return.getProviderDemographicDetails().addAll(_returnProviderDemographicDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
