
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.rxClaimsLookupProd;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-11T17:05:00.383+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "RXClaimsLookUpService",
                      portName = "RXClaimsLookUpServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-svcs.optum.com:8443/rqns-services-web/services/RXClaimsLookUpService?wsdl",
                      endpointInterface = "com.optum.rqns.services.rxClaimsLookupProd.RXClaimsLookUpService")
                      
public class RXClaimsLookUpServiceImpl implements RXClaimsLookUpService {

    private static final Logger LOG = Logger.getLogger(RXClaimsLookUpServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.rxClaimsLookupProd.RXClaimsLookUpService#getRXClaimsByMbrIDAndClient(java.lang.String  memberIdentifier ,)java.lang.String  memberModifier ,)java.lang.String  clientGuid ,)com.optum.rqns.services.rxClaimsLookupProd.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.rxClaimsLookupProd.RxClaimsInfo getRXClaimsByMbrIDAndClient(java.lang.String memberIdentifier,java.lang.String memberModifier,java.lang.String clientGuid,com.optum.rqns.services.rxClaimsLookupProd.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getRXClaimsByMbrIDAndClient");
        System.out.println(memberIdentifier);
        System.out.println(memberModifier);
        System.out.println(clientGuid);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.rxClaimsLookupProd.RxClaimsInfo _return = new com.optum.rqns.services.rxClaimsLookupProd.RxClaimsInfo();
            _return.setReturnCode(Integer.valueOf(-211081697));
            _return.setReturnCodeDesc("ReturnCodeDesc1470597748");
            java.util.List<com.optum.rqns.services.rxClaimsLookupProd.RxClaimDetails> _returnRxClaimDetails = new java.util.ArrayList<com.optum.rqns.services.rxClaimsLookupProd.RxClaimDetails>();
            com.optum.rqns.services.rxClaimsLookupProd.RxClaimDetails _returnRxClaimDetailsVal1 = new com.optum.rqns.services.rxClaimsLookupProd.RxClaimDetails();
            _returnRxClaimDetailsVal1.setMemberGlobalId("MemberGlobalId956613993");
            _returnRxClaimDetailsVal1.setMemberIdentifier("MemberIdentifier-429781893");
            _returnRxClaimDetailsVal1.setMemberModifierId("MemberModifierId-1484912618");
            _returnRxClaimDetailsVal1.setNdcDesc("NdcDesc1851094567");
            _returnRxClaimDetailsVal1.setNdcCode("NdcCode-745288813");
            _returnRxClaimDetailsVal1.setDateFilled(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-08-11T17:05:00.383+05:30"));
            _returnRxClaimDetailsVal1.setQuantity("Quantity882309932");
            _returnRxClaimDetailsVal1.setDateSupply("DateSupply1646437990");
            _returnRxClaimDetailsVal1.setProviderFirstName("ProviderFirstName218141180");
            _returnRxClaimDetailsVal1.setProviderLastName("ProviderLastName1785358730");
            _returnRxClaimDetailsVal1.setProviderMiddleName("ProviderMiddleName-2102201506");
            _returnRxClaimDetails.add(_returnRxClaimDetailsVal1);
            _return.getRxClaimDetails().addAll(_returnRxClaimDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
