package com.optum.rqns.services.rxClaimsLookupProd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * The service port type for RXClaimsLookUpService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-11T17:05:00.398+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://services.rqns.optum.com/", name = "RXClaimsLookUpService")
@XmlSeeAlso({ObjectFactory.class})
public interface RXClaimsLookUpService {

    /**
     * The operation gets RX Claims by member ID and client name
     */
    @WebMethod(action = "getRXClaimsByMbrIDAndClient")
    @RequestWrapper(localName = "getRXClaimsByMbrIDAndClient", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.rxClaimsLookupProd.GetRXClaimsByMbrIDAndClient")
    @ResponseWrapper(localName = "getRXClaimsByMbrIDAndClientResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.rxClaimsLookupProd.GetRXClaimsByMbrIDAndClientResponse")
    @WebResult(name = "rxClaimInfo", targetNamespace = "")
    public com.optum.rqns.services.rxClaimsLookupProd.RxClaimsInfo getRXClaimsByMbrIDAndClient(
        @WebParam(name = "memberIdentifier", targetNamespace = "")
        java.lang.String memberIdentifier,
        @WebParam(name = "memberModifier", targetNamespace = "")
        java.lang.String memberModifier,
        @WebParam(name = "clientGuid", targetNamespace = "")
        java.lang.String clientGuid,
        @WebParam(name = "metaData", targetNamespace = "")
        com.optum.rqns.services.rxClaimsLookupProd.ServiceMetaData metaData
    ) throws ServiceException_Exception;
}
