
package com.optum.rqns.services.rxClaimsLookupProd;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-11T17:05:00.258+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class RXClaimsLookUpService_RXClaimsLookUpServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "RXClaimsLookUpService");

    private RXClaimsLookUpService_RXClaimsLookUpServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RXClaimsLookUpService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RXClaimsLookUpService_Service ss = new RXClaimsLookUpService_Service(wsdlURL, SERVICE_NAME);
        RXClaimsLookUpService port = ss.getRXClaimsLookUpServiceImplPort();  
        
        {
        System.out.println("Invoking getRXClaimsByMbrIDAndClient...");
        java.lang.String _getRXClaimsByMbrIDAndClient_memberIdentifier = "_getRXClaimsByMbrIDAndClient_memberIdentifier-953589782";
        java.lang.String _getRXClaimsByMbrIDAndClient_memberModifier = "_getRXClaimsByMbrIDAndClient_memberModifier10944763";
        java.lang.String _getRXClaimsByMbrIDAndClient_clientGuid = "_getRXClaimsByMbrIDAndClient_clientGuid-1085797262";
        com.optum.rqns.services.rxClaimsLookupProd.ServiceMetaData _getRXClaimsByMbrIDAndClient_metaData = new com.optum.rqns.services.rxClaimsLookupProd.ServiceMetaData();
        _getRXClaimsByMbrIDAndClient_metaData.setAppId("AppId-454157690");
        try {
            com.optum.rqns.services.rxClaimsLookupProd.RxClaimsInfo _getRXClaimsByMbrIDAndClient__return = port.getRXClaimsByMbrIDAndClient(_getRXClaimsByMbrIDAndClient_memberIdentifier, _getRXClaimsByMbrIDAndClient_memberModifier, _getRXClaimsByMbrIDAndClient_clientGuid, _getRXClaimsByMbrIDAndClient_metaData);
            System.out.println("getRXClaimsByMbrIDAndClient.result=" + _getRXClaimsByMbrIDAndClient__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
