package com.optum.rqns.services.medicareDemographyTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * The service port type for MemberDemographicService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-11T17:10:23.504+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://services.rqns.optum.com/", name = "MemberDemographicService")
@XmlSeeAlso({ObjectFactory.class})
public interface MemberDemographicService {

    /**
     * The operation fetches the latest medicare member demographic information by member hic number and client ID
     */
    @WebMethod(action = "getMedicareMemberLatestDemographicInfo")
    @RequestWrapper(localName = "getMedicareMemberLatestDemographicInfo", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.medicareDemographyTest.GetMedicareMemberLatestDemographicInfo")
    @ResponseWrapper(localName = "getMedicareMemberLatestDemographicInfoResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.medicareDemographyTest.GetMedicareMemberLatestDemographicInfoResponse")
    @WebResult(name = "medicareMemberDemographicInfo", targetNamespace = "")
    public com.optum.rqns.services.medicareDemographyTest.MedicareMemberDemographicInfo getMedicareMemberLatestDemographicInfo(
        @WebParam(name = "mbrHicNbr", targetNamespace = "")
        java.lang.String mbrHicNbr,
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.String clientId,
        @WebParam(name = "metaData", targetNamespace = "")
        com.optum.rqns.services.medicareDemographyTest.ServiceMetaData metaData
    ) throws ServiceException_Exception;

    /**
     * The operation fetches the medicare member demographic information by member hic number and client ID
     */
    @WebMethod(action = "getMedicareMemberListInfoByHicId")
    @RequestWrapper(localName = "getMedicareMemberListInfoByHicId", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.medicareDemographyTest.GetMedicareMemberListInfoByHicId")
    @ResponseWrapper(localName = "getMedicareMemberListInfoByHicIdResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.medicareDemographyTest.GetMedicareMemberListInfoByHicIdResponse")
    @WebResult(name = "medicareMemberDemographicInfoList", targetNamespace = "")
    public com.optum.rqns.services.medicareDemographyTest.MedicareMemberDemographicInfoList getMedicareMemberListInfoByHicId(
        @WebParam(name = "mbrHicNum", targetNamespace = "")
        java.lang.String mbrHicNum,
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.String clientId,
        @WebParam(name = "metaData", targetNamespace = "")
        com.optum.rqns.services.medicareDemographyTest.ServiceMetaData metaData
    ) throws ServiceException_Exception;

	/**
     * The operation fetches the medicare member demographic information by member card ID and client ID
     */
    @WebMethod(action = "getMedicareMemberListInfoByCardId")
    @RequestWrapper(localName = "getMedicareMemberListInfoByCardId", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.medicareDemographyTest.GetMedicareMemberListInfoByCardId")
    @ResponseWrapper(localName = "getMedicareMemberListInfoByCardIdResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.medicareDemographyTest.GetMedicareMemberListInfoByCardIdResponse")
    @WebResult(name = "medicareMemberDemographicInfoList", targetNamespace = "")
    public com.optum.rqns.services.medicareDemographyTest.MedicareMemberDemographicInfoList getMedicareMemberListInfoByCardId(
        @WebParam(name = "mbrCardId", targetNamespace = "")
        java.lang.String mbrCardId,
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.String clientId,
        @WebParam(name = "metaData", targetNamespace = "")
        com.optum.rqns.services.medicareDemographyTest.ServiceMetaData metaData
    ) throws ServiceException_Exception;

	/**
     * The operation fetches the medicare member demographic information by member hic number and client ID
     */
//    @WebMethod(action = "getMedicareMemberListInfoByHicId")
//    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
//    @WebResult(name = "getMedicareMemberListInfoByHicIdResponse", targetNamespace = "http://services.rqns.optum.com/", partName = "getMedicareMemberListInfoByHicIdResponse")
    public GetMedicareMemberListInfoByHicIdResponse getMedicareMemberListInfoByHicId(
        @WebParam(partName = "getMedicareMemberListInfoByHicId", name = "getMedicareMemberListInfoByHicId", targetNamespace = "http://services.rqns.optum.com/")
        GetMedicareMemberListInfoByHicId getMedicareMemberListInfoByHicId
    ) throws ServiceException_Exception;

    /**
     * The operation fetches the medicare member demographic information by member card ID and client ID
     */
//    @WebMethod(action = "getMedicareMemberListInfoByCardId")
//    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
//    @WebResult(name = "getMedicareMemberListInfoByCardIdResponse", targetNamespace = "http://services.rqns.optum.com/", partName = "getMedicareMemberListInfoByCardIdResponse")
    public GetMedicareMemberListInfoByCardIdResponse getMedicareMemberListInfoByCardId(
        @WebParam(partName = "getMedicareMemberListInfoByCardId", name = "getMedicareMemberListInfoByCardId", targetNamespace = "http://services.rqns.optum.com/")
        GetMedicareMemberListInfoByCardId getMedicareMemberListInfoByCardId
    ) throws ServiceException_Exception;
}
