
package com.optum.rqns.services.tinTest;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;

import javax.xml.namespace.QName;

import com.optum.rqns.services.utils.DataBaseConnect;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-27T14:29:53.862+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class ProviderTinService_ProviderTinServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "providerTinService");

    public ProviderTinService_ProviderTinServiceImplPort_Client() {
    }

    public  String tinServiceCall() throws java.lang.Exception {
    	String sReturn="";
    /*	System.setProperty("javax.net.ssl.keyStore","C:/CRQS/Webservices/Soap/rqns_tst.jks");
        System.setProperty("javax.net.ssl.keyStorePassword","changeit");
        System.setProperty("javax.net.ssl.trustStore","C:/CRQS/Webservices/Soap/cpc_client_truststore.jks");
        System.setProperty("javax.net.ssl.trustStorePassword","changeit");*/
        String sNpi="";
        String sProvName="";
        int iReturnCode=0;
        String sReturnDesc="";
        
        URL wsdlURL = ProviderTinService_Service.WSDL_LOCATION;
       
      
        ProviderTinService_Service ss = new ProviderTinService_Service(wsdlURL, SERVICE_NAME);
        ProviderTinService port = ss.getProviderTinServiceImplPort();  
        
        {
        System.out.println("Invoking getProviderTinInfo...");
        
        String sRequestSql="select distinct prov1.prov_enty_extr_id, prov2.prov_enty_extr_nm";
        sRequestSql=sRequestSql+" from prov_enty_extr_id prov1, prov_enty_extr_id prov2 where prov1.prov_enty_extr_id_typ_cd = 'NPI'";
        sRequestSql=sRequestSql+"  and prov2.prov_enty_extr_id_typ_cd = 'TIN'";
        sRequestSql=sRequestSql+"  and prov1.prov_enty_id = prov2.prov_enty_id and prov1.prov_enty_mod_id = prov2.prov_enty_mod_id";
        sRequestSql=sRequestSql+"  and prov1.clnt_guid = prov2.clnt_guid ";
        
        ResultSet rs=DataBaseConnect.getRsList("TEST", sRequestSql);
        int iCount=0;
         while (rs.next()){
        	 sNpi = rs.getString(1);
        	 sProvName = rs.getString(2);
         	break;
         }
         
         System.out.println("npi is"+sNpi );
         String sNpi1="";
         String sTin1="";
         String sProvName1="";
        com.optum.rqns.services.tinTest.GetProviderTinInfo _getProviderTinInfo_getProviderTinInfo = new com.optum.rqns.services.tinTest.GetProviderTinInfo();
        _getProviderTinInfo_getProviderTinInfo.setProviderNpiID(sNpi);
        _getProviderTinInfo_getProviderTinInfo.setProviderName(sProvName);
        com.optum.rqns.services.tinTest.ServiceMetaData _getProviderTinInfo_getProviderTinInfoMetaData = new com.optum.rqns.services.tinTest.ServiceMetaData();
        _getProviderTinInfo_getProviderTinInfoMetaData.setAppId("5317c8af4dd6bec7b46c2083018b8ae6");
        _getProviderTinInfo_getProviderTinInfo.setMetaData(_getProviderTinInfo_getProviderTinInfoMetaData);
        try {
        	String sResponseSql="select distinct prov1.prov_enty_extr_id,  prov2.prov_enty_extr_id,prov2.prov_enty_extr_nm";
        	sResponseSql=sResponseSql+" from prov_enty_extr_id prov1, prov_enty_extr_id prov2 where prov1.prov_enty_extr_id_typ_cd = 'NPI'";
        	sResponseSql=sResponseSql+" and   prov1.prov_enty_extr_id ='"+sNpi+"'   and prov2.prov_enty_extr_id_typ_cd = 'TIN'";
        	sResponseSql=sResponseSql+"  and prov1.prov_enty_id = prov2.prov_enty_id and prov1.prov_enty_mod_id = prov2.prov_enty_mod_id";
        	sResponseSql=sResponseSql+"  and prov1.clnt_guid = prov2.clnt_guid and    upper(prov2.prov_enty_extr_nm) like upper('%'||'"+sProvName+"'||'%') ";
            com.optum.rqns.services.tinTest.GetProviderTinInfoResponse _getProviderTinInfo__return = port.getProviderTinInfo(_getProviderTinInfo_getProviderTinInfo);
             iReturnCode=_getProviderTinInfo__return.providerTinInfo.returnCode;
         //    sReturnDesc=   _getProviderTinInfo__return.providerTinInfo.
            //  System.out.println("getProviderTinInfo.result=" + _getProviderTinInfo__return.toString());
            //  System.out.println("getProviderTinInfo.result=" + _getProviderTinInfo__return.providerTinInfo.toString());
              ResultSet rs1=DataBaseConnect.getRsList("TEST", sResponseSql);
              int iCount1=0;
               while (rs1.next()){
              	 sNpi1 = rs1.getString(1);
              	 sTin1 = rs1.getString(2);
              	 sProvName1 = rs1.getString(3);
              	// sProvName = rs1.getString(2);
               	break;
               }
              
              System.out.println("From Service");
              System.out.println(_getProviderTinInfo__return.providerTinInfo.providerNpiID);
             System.out.println(_getProviderTinInfo__return.providerTinInfo.providerTin);
             System.out.println(_getProviderTinInfo__return.providerTinInfo.providerTinName);
          
             
             System.out.println("From DB");
             System.out.println(sNpi1);
            System.out.println(sTin1);
            System.out.println(sProvName1);
            
            if (_getProviderTinInfo__return.providerTinInfo.providerNpiID.equals(sNpi1) &&
          		  _getProviderTinInfo__return.providerTinInfo.providerTin.equals(sTin1) &&
          		  _getProviderTinInfo__return.providerTinInfo.providerTinName.equals(sProvName1))
            {
          	  sReturn=" *********************************Passed*******************************";
          	  sReturn=sReturn+"Request :- NPI-------  "+sNpi1;
          	  sReturn=sReturn+"     - TIN-------  "+sTin1;
          	  
          	  sReturn=sReturn+"******************Response****************** :- NPI-------  "+_getProviderTinInfo__return.providerTinInfo.providerNpiID;
          	  sReturn=sReturn+"     - TIN-------  "+_getProviderTinInfo__return.providerTinInfo.providerTin;
          	  
          	  sReturn=sReturn+"     - TIN Name-------  "+_getProviderTinInfo__return.providerTinInfo.providerTinName;
          	  
          	  
            }
            else
            {
          	  sReturn=" *********************************Failed*******************************";
          	  sReturn=sReturn+"Request :- NPI-------  "+sNpi1;
          	  sReturn=sReturn+"     - TIN-------  "+sTin1;
          	  
          	  sReturn=sReturn+"******************Response****************** :- NPI-------  "+_getProviderTinInfo__return.providerTinInfo.providerNpiID;
          	  sReturn=sReturn+"     - TIN-------  "+_getProviderTinInfo__return.providerTinInfo.providerTin;
          	  
          	  sReturn=sReturn+"     - TIN Name-------  "+_getProviderTinInfo__return.providerTinInfo.providerTinName;
            }
             
             // _getProviderTinInfo__return.providerTinInfo.p
            
            
        } catch (ServiceException_Exception e) { 
        	sReturn=iReturnCode+sReturnDesc+e.getMessage();
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
        
        catch (NullPointerException e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
            sReturn=iReturnCode+sReturnDesc+e.getMessage();
        }
            }
System.out.println(sReturn);
     //  System.exit(0);
return sReturn;
    }

}
