package com.optum.rqns.services.tinTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * The service port type for ProviderTinService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-27T14:29:54.003+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://services.rqns.optum.com/", name = "ProviderTinService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProviderTinService {

    /**
     * The operation gets provider TIN info by provider NPI ID and provider name
     */
    @WebMethod(action = "getProviderTinInfo")
    @WebResult(name = "getProviderTinInfoResponse", targetNamespace = "http://services.rqns.optum.com/", partName = "getProviderTinInfoResponse")
    public GetProviderTinInfoResponse getProviderTinInfo(
        @WebParam(partName = "getProviderTinInfo", name = "getProviderTinInfo", targetNamespace = "http://services.rqns.optum.com/")
        GetProviderTinInfo getProviderTinInfo
    ) throws ServiceException_Exception;
}
