package com.optum.rqns.services.gap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The service name for GapStatusInfoService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-03T15:51:15.908+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "GapStatusInfoServiceImpl", 
                  wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8444/rqns-services-web/services/GapStatusInfoService?wsdl",
                  targetNamespace = "http://services.rqns.optum.com/") 
public class GapStatusInfoServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.rqns.optum.com/", "GapStatusInfoServiceImpl");
    public final static QName GapStatusInfoServiceImplPort = new QName("http://services.rqns.optum.com/", "GapStatusInfoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://trustbroker-stg-svcs.optum.com:8444/rqns-services-web/services/GapStatusInfoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GapStatusInfoServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://trustbroker-stg-svcs.optum.com:8444/rqns-services-web/services/GapStatusInfoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GapStatusInfoServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GapStatusInfoServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GapStatusInfoServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GapStatusInfoServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GapStatusInfoServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GapStatusInfoServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * The service port for GapStatusInfoService
     *
     * @return
     *     returns GapStatusInfoService
     */
    @WebEndpoint(name = "GapStatusInfoServiceImplPort")
    public GapStatusInfoService getGapStatusInfoServiceImplPort() {
        return super.getPort(GapStatusInfoServiceImplPort, GapStatusInfoService.class);
    }

    /**
     * The service port for GapStatusInfoService
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GapStatusInfoService
     */
    @WebEndpoint(name = "GapStatusInfoServiceImplPort")
    public GapStatusInfoService getGapStatusInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(GapStatusInfoServiceImplPort, GapStatusInfoService.class, features);
    }

}
