package com.optum.rqns.services.medicaideligiblity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * The service port type for MedicaidMemberEligibilityService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-25T16:51:33.569+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://services.rqns.optum.com/", name = "MedicaidMemberEligibilityService")
@XmlSeeAlso({ObjectFactory.class})
public interface MedicaidMemberEligibilityService {

    /**
     * The operation fetches member eligibility information by global member id and client name
     */
    @WebMethod(action = "getEligibleMcaidMembersByGlbMbrIDAndClient")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEligibleMcaidMembersByGlbMbrIDAndClientResponse", targetNamespace = "http://services.rqns.optum.com/", partName = "getEligibleMcaidMembersByGlbMbrIDAndClientResponse")
    public GetEligibleMcaidMembersByGlbMbrIDAndClientResponse getEligibleMcaidMembersByGlbMbrIDAndClient(
        @WebParam(partName = "getEligibleMcaidMembersByGlbMbrIDAndClient", name = "getEligibleMcaidMembersByGlbMbrIDAndClient", targetNamespace = "http://services.rqns.optum.com/")
        GetEligibleMcaidMembersByGlbMbrIDAndClient getEligibleMcaidMembersByGlbMbrIDAndClient
    ) throws ServiceException_Exception;

    /**
     * The operation fetches member eligibility information by member id and client name
     */
    @WebMethod(action = "getEligibleMcaidMembersByMbrIDAndClient")
    @RequestWrapper(localName = "getEligibleMcaidMembersByMbrIDAndClient", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.medicaideligiblity.GetEligibleMcaidMembersByMbrIDAndClient")
    @ResponseWrapper(localName = "getEligibleMcaidMembersByMbrIDAndClientResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.medicaideligiblity.GetEligibleMcaidMembersByMbrIDAndClientResponse")
    @WebResult(name = "eligibilityInfo", targetNamespace = "")
    public com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityInfo getEligibleMcaidMembersByMbrIDAndClient(
        @WebParam(name = "eligStrtDt", targetNamespace = "")
        java.lang.String eligStrtDt,
        @WebParam(name = "eligEndDt", targetNamespace = "")
        java.lang.String eligEndDt,
        @WebParam(name = "clientName", targetNamespace = "")
        java.lang.String clientName,
        @WebParam(name = "memberID", targetNamespace = "")
        java.lang.String memberID,
        @WebParam(name = "modifierID", targetNamespace = "")
        java.lang.String modifierID,
        @WebParam(name = "metaData", targetNamespace = "")
        com.optum.rqns.services.medicaideligiblity.ServiceMetaData metaData
    ) throws ServiceException_Exception;
}
