
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.medicaideligiblity;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-25T16:51:33.554+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "medicaidMemberEligibilityService",
                      portName = "MedicaidMemberEligibilityServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/rqns-services-web/services/medicaidMemberEligibilityService?wsdl",
                      endpointInterface = "com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityService")
                      
public class MedicaidMemberEligibilityServiceImpl implements MedicaidMemberEligibilityService {

    private static final Logger LOG = Logger.getLogger(MedicaidMemberEligibilityServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityService#getEligibleMcaidMembersByGlbMbrIDAndClient(com.optum.rqns.services.medicaideligiblity.GetEligibleMcaidMembersByGlbMbrIDAndClient  getEligibleMcaidMembersByGlbMbrIDAndClient )*
     */
    public com.optum.rqns.services.medicaideligiblity.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse getEligibleMcaidMembersByGlbMbrIDAndClient(GetEligibleMcaidMembersByGlbMbrIDAndClient getEligibleMcaidMembersByGlbMbrIDAndClient) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleMcaidMembersByGlbMbrIDAndClient");
        System.out.println(getEligibleMcaidMembersByGlbMbrIDAndClient);
        try {
            com.optum.rqns.services.medicaideligiblity.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse _return = new com.optum.rqns.services.medicaideligiblity.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse();
            com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityInfo _returnEligibilityInfo = new com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityDetails> _returnEligibilityInfoMedicaidMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityDetails>();
            com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityDetails _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1 = new com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityDetails();
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setReturnCode(486346425);
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc-1420499245");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource-860924462");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setMemberID("MemberID415600325");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setModifierID("ModifierID-1414744147");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID1719887869");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber965206800");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setPlanDesc("PlanDesc-1675219299");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setLobID("LobID-2146424190");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setLobIDDesc("LobIDDesc-632909418");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setProgramTypeCd("ProgramTypeCd453190113");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setClassID("ClassID-1652003773");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setClassIDDesc("ClassIDDesc870974508");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt1354266186");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt-2095156557");
            _returnEligibilityInfoMedicaidMemberEligibilityDetails.add(_returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1);
            _returnEligibilityInfo.getMedicaidMemberEligibilityDetails().addAll(_returnEligibilityInfoMedicaidMemberEligibilityDetails);
            _returnEligibilityInfo.setErrorMsg("ErrorMsg-295426106");
            _return.setEligibilityInfo(_returnEligibilityInfo);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityService#getEligibleMcaidMembersByMbrIDAndClient(java.lang.String  eligStrtDt ,)java.lang.String  eligEndDt ,)java.lang.String  clientName ,)java.lang.String  memberID ,)java.lang.String  modifierID ,)com.optum.rqns.services.medicaideligiblity.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityInfo getEligibleMcaidMembersByMbrIDAndClient(java.lang.String eligStrtDt,java.lang.String eligEndDt,java.lang.String clientName,java.lang.String memberID,java.lang.String modifierID,com.optum.rqns.services.medicaideligiblity.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleMcaidMembersByMbrIDAndClient");
        System.out.println(eligStrtDt);
        System.out.println(eligEndDt);
        System.out.println(clientName);
        System.out.println(memberID);
        System.out.println(modifierID);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityInfo _return = new com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityDetails> _returnMedicaidMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityDetails>();
            com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityDetails _returnMedicaidMemberEligibilityDetailsVal1 = new com.optum.rqns.services.medicaideligiblity.MedicaidMemberEligibilityDetails();
            _returnMedicaidMemberEligibilityDetailsVal1.setReturnCode(-1345280242);
            _returnMedicaidMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc-2105797873");
            _returnMedicaidMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource360813440");
            _returnMedicaidMemberEligibilityDetailsVal1.setMemberID("MemberID-726119790");
            _returnMedicaidMemberEligibilityDetailsVal1.setModifierID("ModifierID-1950729793");
            _returnMedicaidMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID1307369628");
            _returnMedicaidMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber1918748207");
            _returnMedicaidMemberEligibilityDetailsVal1.setPlanDesc("PlanDesc616298501");
            _returnMedicaidMemberEligibilityDetailsVal1.setLobID("LobID1367559696");
            _returnMedicaidMemberEligibilityDetailsVal1.setLobIDDesc("LobIDDesc1949403163");
            _returnMedicaidMemberEligibilityDetailsVal1.setProgramTypeCd("ProgramTypeCd867072314");
            _returnMedicaidMemberEligibilityDetailsVal1.setClassID("ClassID-602295487");
            _returnMedicaidMemberEligibilityDetailsVal1.setClassIDDesc("ClassIDDesc1888121933");
            _returnMedicaidMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt-747065572");
            _returnMedicaidMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt-179743088");
            _returnMedicaidMemberEligibilityDetails.add(_returnMedicaidMemberEligibilityDetailsVal1);
            _return.getMedicaidMemberEligibilityDetails().addAll(_returnMedicaidMemberEligibilityDetails);
            _return.setErrorMsg("ErrorMsg1884720707");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
