
package com.optum.rqns.services.npiLookupStage;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-11T17:06:04.450+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class ProviderNpiLookUpService_ProviderNpiLookUpServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "providerNpiLookUpService");

    private ProviderNpiLookUpService_ProviderNpiLookUpServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProviderNpiLookUpService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProviderNpiLookUpService_Service ss = new ProviderNpiLookUpService_Service(wsdlURL, SERVICE_NAME);
        ProviderNpiLookUpService port = ss.getProviderNpiLookUpServiceImplPort();  
        
        {
        System.out.println("Invoking getClientP360ProviderInfoByGlobalID...");
        com.optum.rqns.services.npiLookupStage.ServiceMetaData _getClientP360ProviderInfoByGlobalID_metaData = new com.optum.rqns.services.npiLookupStage.ServiceMetaData();
        _getClientP360ProviderInfoByGlobalID_metaData.setAppId("AppId-1751168969");
        java.lang.String _getClientP360ProviderInfoByGlobalID_globalProviderID = "_getClientP360ProviderInfoByGlobalID_globalProviderID-1465296455";
        java.lang.String _getClientP360ProviderInfoByGlobalID_clientName = "_getClientP360ProviderInfoByGlobalID_clientName-1412122733";
        try {
            com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo _getClientP360ProviderInfoByGlobalID__return = port.getClientP360ProviderInfoByGlobalID(_getClientP360ProviderInfoByGlobalID_metaData, _getClientP360ProviderInfoByGlobalID_globalProviderID, _getClientP360ProviderInfoByGlobalID_clientName);
            System.out.println("getClientP360ProviderInfoByGlobalID.result=" + _getClientP360ProviderInfoByGlobalID__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNppesProviderInfoByNpi...");
        com.optum.rqns.services.npiLookupStage.ServiceMetaData _getNppesProviderInfoByNpi_metaData = new com.optum.rqns.services.npiLookupStage.ServiceMetaData();
        _getNppesProviderInfoByNpi_metaData.setAppId("AppId1426763765");
        java.lang.Long _getNppesProviderInfoByNpi_providerNpiID = Long.valueOf(-7297285131444989816l);
        try {
            com.optum.rqns.services.npiLookupStage.ProviderInfo _getNppesProviderInfoByNpi__return = port.getNppesProviderInfoByNpi(_getNppesProviderInfoByNpi_metaData, _getNppesProviderInfoByNpi_providerNpiID);
            System.out.println("getNppesProviderInfoByNpi.result=" + _getNppesProviderInfoByNpi__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getClientProviderInfoByProviderIDAndClientName...");
        com.optum.rqns.services.npiLookupStage.ServiceMetaData _getClientProviderInfoByProviderIDAndClientName_metaData = new com.optum.rqns.services.npiLookupStage.ServiceMetaData();
        _getClientProviderInfoByProviderIDAndClientName_metaData.setAppId("AppId-1889970079");
        java.lang.String _getClientProviderInfoByProviderIDAndClientName_healthPlanProviderID = "_getClientProviderInfoByProviderIDAndClientName_healthPlanProviderID900445168";
        java.lang.String _getClientProviderInfoByProviderIDAndClientName_modifierID = "_getClientProviderInfoByProviderIDAndClientName_modifierID-58702000";
        java.lang.String _getClientProviderInfoByProviderIDAndClientName_clientName = "_getClientProviderInfoByProviderIDAndClientName_clientName-1710725020";
        try {
            com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo _getClientProviderInfoByProviderIDAndClientName__return = port.getClientProviderInfoByProviderIDAndClientName(_getClientProviderInfoByProviderIDAndClientName_metaData, _getClientProviderInfoByProviderIDAndClientName_healthPlanProviderID, _getClientProviderInfoByProviderIDAndClientName_modifierID, _getClientProviderInfoByProviderIDAndClientName_clientName);
            System.out.println("getClientProviderInfoByProviderIDAndClientName.result=" + _getClientProviderInfoByProviderIDAndClientName__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getClientProviderInfoByNpiAndClientName...");
        com.optum.rqns.services.npiLookupStage.ServiceMetaData _getClientProviderInfoByNpiAndClientName_metaData = new com.optum.rqns.services.npiLookupStage.ServiceMetaData();
        _getClientProviderInfoByNpiAndClientName_metaData.setAppId("AppId363236364");
        java.lang.String _getClientProviderInfoByNpiAndClientName_providerNpiId = "_getClientProviderInfoByNpiAndClientName_providerNpiId-505445926";
        java.lang.String _getClientProviderInfoByNpiAndClientName_clientName = "_getClientProviderInfoByNpiAndClientName_clientName492827043";
        try {
            com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo _getClientProviderInfoByNpiAndClientName__return = port.getClientProviderInfoByNpiAndClientName(_getClientProviderInfoByNpiAndClientName_metaData, _getClientProviderInfoByNpiAndClientName_providerNpiId, _getClientProviderInfoByNpiAndClientName_clientName);
            System.out.println("getClientProviderInfoByNpiAndClientName.result=" + _getClientProviderInfoByNpiAndClientName__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
