
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.npiLookupStage;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-11T17:06:04.559+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "providerNpiLookUpService",
                      portName = "ProviderNpiLookUpServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-svcs.optum.com:8443/rqns-services-web/services/providerNpiLookUpService?wsdl",
                      endpointInterface = "com.optum.rqns.services.npiLookupStage.ProviderNpiLookUpService")
                      
public class ProviderNpiLookUpServiceImpl implements ProviderNpiLookUpService {

    private static final Logger LOG = Logger.getLogger(ProviderNpiLookUpServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.npiLookupStage.ProviderNpiLookUpService#getClientP360ProviderInfoByGlobalID(com.optum.rqns.services.npiLookupStage.ServiceMetaData  metaData ,)java.lang.String  globalProviderID ,)java.lang.String  clientName )*
     */
    public com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo getClientP360ProviderInfoByGlobalID(com.optum.rqns.services.npiLookupStage.ServiceMetaData metaData,java.lang.String globalProviderID,java.lang.String clientName) throws ServiceException_Exception    { 
        LOG.info("Executing operation getClientP360ProviderInfoByGlobalID");
        System.out.println(metaData);
        System.out.println(globalProviderID);
        System.out.println(clientName);
        try {
            com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo _return = new com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo();
            _return.setReturnCode(Integer.valueOf(881332912));
            _return.setReturnCodeDesc("ReturnCodeDesc952281738");
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails> _returnProviderDemographicDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails>();
            com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails _returnProviderDemographicDetailsVal1 = new com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails();
            _returnProviderDemographicDetailsVal1.setDataSource("DataSource-527107223");
            _returnProviderDemographicDetailsVal1.setClientGuid("ClientGuid-1566508092");
            _returnProviderDemographicDetailsVal1.setProviderID("ProviderID670406480");
            _returnProviderDemographicDetailsVal1.setGlobalProviderID("GlobalProviderID194753406");
            _returnProviderDemographicDetailsVal1.setProviderModifier("ProviderModifier1680274696");
            _returnProviderDemographicDetailsVal1.setProviderFullName("ProviderFullName-613211746");
            _returnProviderDemographicDetailsVal1.setPhysicianLastName("PhysicianLastName193312087");
            _returnProviderDemographicDetailsVal1.setProviderFirstName("ProviderFirstName-781290787");
            _returnProviderDemographicDetailsVal1.setProviderMiddleName("ProviderMiddleName-345888859");
            _returnProviderDemographicDetailsVal1.setPhysicianNameSuffix("PhysicianNameSuffix1865098074");
            _returnProviderDemographicDetailsVal1.setProviderEntityCapitationInd("ProviderEntityCapitationInd-1492575483");
            _returnProviderDemographicDetailsVal1.setParticipatingStatus("ParticipatingStatus1516817363");
            _returnProviderDemographicDetailsVal1.setProviderContractStartDate("ProviderContractStartDate1142418377");
            _returnProviderDemographicDetailsVal1.setProviderContractEndDate("ProviderContractEndDate406873313");
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderNPI = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderNPI().addAll(_returnProviderDemographicDetailsVal1ProviderNPI);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderTIN = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderTIN().addAll(_returnProviderDemographicDetailsVal1ProviderTIN);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1SpecialtyCode = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getSpecialtyCode().addAll(_returnProviderDemographicDetailsVal1SpecialtyCode);
            com.optum.rqns.services.npiLookupStage.ProviderAffiliationInfo _returnProviderDemographicDetailsVal1ProviderAffiliationInfo = new com.optum.rqns.services.npiLookupStage.ProviderAffiliationInfo();
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderAffiliationDetails> _returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderAffiliationDetails>();
            _returnProviderDemographicDetailsVal1ProviderAffiliationInfo.getProviderAffiliationDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails);
            _returnProviderDemographicDetailsVal1.setProviderAffiliationInfo(_returnProviderDemographicDetailsVal1ProviderAffiliationInfo);
            com.optum.rqns.services.npiLookupStage.ProviderAddressInfo _returnProviderDemographicDetailsVal1ProviderAddressInfo = new com.optum.rqns.services.npiLookupStage.ProviderAddressInfo();
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderAddressDetails> _returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderAddressDetails>();
            _returnProviderDemographicDetailsVal1ProviderAddressInfo.getProviderAddressDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails);
            _returnProviderDemographicDetailsVal1.setProviderAddressInfo(_returnProviderDemographicDetailsVal1ProviderAddressInfo);
            _returnProviderDemographicDetails.add(_returnProviderDemographicDetailsVal1);
            _return.getProviderDemographicDetails().addAll(_returnProviderDemographicDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.npiLookupStage.ProviderNpiLookUpService#getNppesProviderInfoByNpi(com.optum.rqns.services.npiLookupStage.ServiceMetaData  metaData ,)java.lang.Long  providerNpiID )*
     */
    public com.optum.rqns.services.npiLookupStage.ProviderInfo getNppesProviderInfoByNpi(com.optum.rqns.services.npiLookupStage.ServiceMetaData metaData,java.lang.Long providerNpiID) throws ServiceException_Exception    { 
        LOG.info("Executing operation getNppesProviderInfoByNpi");
        System.out.println(metaData);
        System.out.println(providerNpiID);
        try {
            com.optum.rqns.services.npiLookupStage.ProviderInfo _return = new com.optum.rqns.services.npiLookupStage.ProviderInfo();
            _return.setReturnCode(Integer.valueOf(-202774288));
            _return.setReturnCodeDesc("ReturnCodeDesc1063996903");
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderDetails> _returnProviderDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderDetails>();
            com.optum.rqns.services.npiLookupStage.ProviderDetails _returnProviderDetailsVal1 = new com.optum.rqns.services.npiLookupStage.ProviderDetails();
            _returnProviderDetailsVal1.setDataSource("DataSource-1648815640");
            _returnProviderDetailsVal1.setProviderNPI(-862859763080121216l);
            _returnProviderDetailsVal1.setProvOrgName("ProvOrgName241989725");
            _returnProviderDetailsVal1.setProvLastName("ProvLastName1985309690");
            _returnProviderDetailsVal1.setProvFirstName("ProvFirstName763746440");
            _returnProviderDetailsVal1.setProvMiddleName("ProvMiddleName-1435976289");
            _returnProviderDetailsVal1.setProvEnumDate("ProvEnumDate608325595");
            _returnProviderDetailsVal1.setLastUpdateDate("LastUpdateDate-1659773878");
            _returnProviderDetailsVal1.setNpiDeactDate("NpiDeactDate-1635625889");
            _returnProviderDetailsVal1.setNpiReactDate("NpiReactDate397822897");
            _returnProviderDetailsVal1.setProvAddrTypeCode("ProvAddrTypeCode-440587698");
            _returnProviderDetailsVal1.setProvAddrLine1("ProvAddrLine11139801485");
            _returnProviderDetailsVal1.setProvAddrLine2("ProvAddrLine2217052213");
            _returnProviderDetailsVal1.setProvCity("ProvCity-1422563902");
            _returnProviderDetailsVal1.setProvState("ProvState-2092378866");
            _returnProviderDetailsVal1.setProvZip("ProvZip1960818741");
            java.util.List<java.lang.String> _returnProviderDetailsVal1ProvSpecialtyCode = new java.util.ArrayList<java.lang.String>();
            _returnProviderDetailsVal1.getProvSpecialtyCode().addAll(_returnProviderDetailsVal1ProvSpecialtyCode);
            java.util.List<java.lang.String> _returnProviderDetailsVal1ProvOtherID = new java.util.ArrayList<java.lang.String>();
            _returnProviderDetailsVal1.getProvOtherID().addAll(_returnProviderDetailsVal1ProvOtherID);
            _returnProviderDetails.add(_returnProviderDetailsVal1);
            _return.getProviderDetails().addAll(_returnProviderDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.npiLookupStage.ProviderNpiLookUpService#getClientProviderInfoByProviderIDAndClientName(com.optum.rqns.services.npiLookupStage.ServiceMetaData  metaData ,)java.lang.String  healthPlanProviderID ,)java.lang.String  modifierID ,)java.lang.String  clientName )*
     */
    public com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo getClientProviderInfoByProviderIDAndClientName(com.optum.rqns.services.npiLookupStage.ServiceMetaData metaData,java.lang.String healthPlanProviderID,java.lang.String modifierID,java.lang.String clientName) throws ServiceException_Exception    { 
        LOG.info("Executing operation getClientProviderInfoByProviderIDAndClientName");
        System.out.println(metaData);
        System.out.println(healthPlanProviderID);
        System.out.println(modifierID);
        System.out.println(clientName);
        try {
            com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo _return = new com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo();
            _return.setReturnCode(Integer.valueOf(1359534127));
            _return.setReturnCodeDesc("ReturnCodeDesc-447718914");
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails> _returnProviderDemographicDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails>();
            com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails _returnProviderDemographicDetailsVal1 = new com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails();
            _returnProviderDemographicDetailsVal1.setDataSource("DataSource234322239");
            _returnProviderDemographicDetailsVal1.setClientGuid("ClientGuid348412167");
            _returnProviderDemographicDetailsVal1.setProviderID("ProviderID1496372876");
            _returnProviderDemographicDetailsVal1.setGlobalProviderID("GlobalProviderID1437124709");
            _returnProviderDemographicDetailsVal1.setProviderModifier("ProviderModifier-1523850630");
            _returnProviderDemographicDetailsVal1.setProviderFullName("ProviderFullName-1482949398");
            _returnProviderDemographicDetailsVal1.setPhysicianLastName("PhysicianLastName1494146278");
            _returnProviderDemographicDetailsVal1.setProviderFirstName("ProviderFirstName418981054");
            _returnProviderDemographicDetailsVal1.setProviderMiddleName("ProviderMiddleName256838573");
            _returnProviderDemographicDetailsVal1.setPhysicianNameSuffix("PhysicianNameSuffix210855426");
            _returnProviderDemographicDetailsVal1.setProviderEntityCapitationInd("ProviderEntityCapitationInd-1459314248");
            _returnProviderDemographicDetailsVal1.setParticipatingStatus("ParticipatingStatus-1506286644");
            _returnProviderDemographicDetailsVal1.setProviderContractStartDate("ProviderContractStartDate1884755519");
            _returnProviderDemographicDetailsVal1.setProviderContractEndDate("ProviderContractEndDate-2069000707");
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderNPI = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderNPI().addAll(_returnProviderDemographicDetailsVal1ProviderNPI);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderTIN = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderTIN().addAll(_returnProviderDemographicDetailsVal1ProviderTIN);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1SpecialtyCode = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getSpecialtyCode().addAll(_returnProviderDemographicDetailsVal1SpecialtyCode);
            com.optum.rqns.services.npiLookupStage.ProviderAffiliationInfo _returnProviderDemographicDetailsVal1ProviderAffiliationInfo = new com.optum.rqns.services.npiLookupStage.ProviderAffiliationInfo();
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderAffiliationDetails> _returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderAffiliationDetails>();
            _returnProviderDemographicDetailsVal1ProviderAffiliationInfo.getProviderAffiliationDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails);
            _returnProviderDemographicDetailsVal1.setProviderAffiliationInfo(_returnProviderDemographicDetailsVal1ProviderAffiliationInfo);
            com.optum.rqns.services.npiLookupStage.ProviderAddressInfo _returnProviderDemographicDetailsVal1ProviderAddressInfo = new com.optum.rqns.services.npiLookupStage.ProviderAddressInfo();
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderAddressDetails> _returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderAddressDetails>();
            _returnProviderDemographicDetailsVal1ProviderAddressInfo.getProviderAddressDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails);
            _returnProviderDemographicDetailsVal1.setProviderAddressInfo(_returnProviderDemographicDetailsVal1ProviderAddressInfo);
            _returnProviderDemographicDetails.add(_returnProviderDemographicDetailsVal1);
            _return.getProviderDemographicDetails().addAll(_returnProviderDemographicDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.npiLookupStage.ProviderNpiLookUpService#getClientProviderInfoByNpiAndClientName(com.optum.rqns.services.npiLookupStage.ServiceMetaData  metaData ,)java.lang.String  providerNpiId ,)java.lang.String  clientName )*
     */
    public com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo getClientProviderInfoByNpiAndClientName(com.optum.rqns.services.npiLookupStage.ServiceMetaData metaData,java.lang.String providerNpiId,java.lang.String clientName) throws ServiceException_Exception    { 
        LOG.info("Executing operation getClientProviderInfoByNpiAndClientName");
        System.out.println(metaData);
        System.out.println(providerNpiId);
        System.out.println(clientName);
        try {
            com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo _return = new com.optum.rqns.services.npiLookupStage.ProviderDemographicInfo();
            _return.setReturnCode(Integer.valueOf(-424580576));
            _return.setReturnCodeDesc("ReturnCodeDesc1822672831");
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails> _returnProviderDemographicDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails>();
            com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails _returnProviderDemographicDetailsVal1 = new com.optum.rqns.services.npiLookupStage.ProviderDemographicDetails();
            _returnProviderDemographicDetailsVal1.setDataSource("DataSource-1264316553");
            _returnProviderDemographicDetailsVal1.setClientGuid("ClientGuid1012894124");
            _returnProviderDemographicDetailsVal1.setProviderID("ProviderID-1095440411");
            _returnProviderDemographicDetailsVal1.setGlobalProviderID("GlobalProviderID-219938835");
            _returnProviderDemographicDetailsVal1.setProviderModifier("ProviderModifier1648670");
            _returnProviderDemographicDetailsVal1.setProviderFullName("ProviderFullName-999910955");
            _returnProviderDemographicDetailsVal1.setPhysicianLastName("PhysicianLastName-1481411654");
            _returnProviderDemographicDetailsVal1.setProviderFirstName("ProviderFirstName-220327999");
            _returnProviderDemographicDetailsVal1.setProviderMiddleName("ProviderMiddleName916406882");
            _returnProviderDemographicDetailsVal1.setPhysicianNameSuffix("PhysicianNameSuffix51594567");
            _returnProviderDemographicDetailsVal1.setProviderEntityCapitationInd("ProviderEntityCapitationInd2129471427");
            _returnProviderDemographicDetailsVal1.setParticipatingStatus("ParticipatingStatus-1316048653");
            _returnProviderDemographicDetailsVal1.setProviderContractStartDate("ProviderContractStartDate-559416836");
            _returnProviderDemographicDetailsVal1.setProviderContractEndDate("ProviderContractEndDate412252205");
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderNPI = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderNPI().addAll(_returnProviderDemographicDetailsVal1ProviderNPI);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1ProviderTIN = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getProviderTIN().addAll(_returnProviderDemographicDetailsVal1ProviderTIN);
            java.util.List<java.lang.String> _returnProviderDemographicDetailsVal1SpecialtyCode = new java.util.ArrayList<java.lang.String>();
            _returnProviderDemographicDetailsVal1.getSpecialtyCode().addAll(_returnProviderDemographicDetailsVal1SpecialtyCode);
            com.optum.rqns.services.npiLookupStage.ProviderAffiliationInfo _returnProviderDemographicDetailsVal1ProviderAffiliationInfo = new com.optum.rqns.services.npiLookupStage.ProviderAffiliationInfo();
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderAffiliationDetails> _returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderAffiliationDetails>();
            _returnProviderDemographicDetailsVal1ProviderAffiliationInfo.getProviderAffiliationDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAffiliationInfoProviderAffiliationDetails);
            _returnProviderDemographicDetailsVal1.setProviderAffiliationInfo(_returnProviderDemographicDetailsVal1ProviderAffiliationInfo);
            com.optum.rqns.services.npiLookupStage.ProviderAddressInfo _returnProviderDemographicDetailsVal1ProviderAddressInfo = new com.optum.rqns.services.npiLookupStage.ProviderAddressInfo();
            java.util.List<com.optum.rqns.services.npiLookupStage.ProviderAddressDetails> _returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails = new java.util.ArrayList<com.optum.rqns.services.npiLookupStage.ProviderAddressDetails>();
            _returnProviderDemographicDetailsVal1ProviderAddressInfo.getProviderAddressDetails().addAll(_returnProviderDemographicDetailsVal1ProviderAddressInfoProviderAddressDetails);
            _returnProviderDemographicDetailsVal1.setProviderAddressInfo(_returnProviderDemographicDetailsVal1ProviderAddressInfo);
            _returnProviderDemographicDetails.add(_returnProviderDemographicDetailsVal1);
            _return.getProviderDemographicDetails().addAll(_returnProviderDemographicDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
