
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.medicareEligiblityProd;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-11T17:09:05.967+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "medicaidMemberEligibilityService",
                      portName = "MedicaidMemberEligibilityServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-svcs.optum.com:8443/rqns-services-web/services/medicaidMemberEligibilityService?wsdl",
                      endpointInterface = "com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityService")
                      
public class MedicaidMemberEligibilityServiceImpl implements MedicaidMemberEligibilityService {

    private static final Logger LOG = Logger.getLogger(MedicaidMemberEligibilityServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityService#getEligibleMcaidMembersByGlbMbrIDAndClient(com.optum.rqns.services.medicareEligiblityProd.GetEligibleMcaidMembersByGlbMbrIDAndClient  getEligibleMcaidMembersByGlbMbrIDAndClient )*
     */
    public com.optum.rqns.services.medicareEligiblityProd.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse getEligibleMcaidMembersByGlbMbrIDAndClient(GetEligibleMcaidMembersByGlbMbrIDAndClient getEligibleMcaidMembersByGlbMbrIDAndClient) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleMcaidMembersByGlbMbrIDAndClient");
        System.out.println(getEligibleMcaidMembersByGlbMbrIDAndClient);
        try {
            com.optum.rqns.services.medicareEligiblityProd.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse _return = new com.optum.rqns.services.medicareEligiblityProd.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse();
            com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityInfo _returnEligibilityInfo = new com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityDetails> _returnEligibilityInfoMedicaidMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityDetails>();
            com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityDetails _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1 = new com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityDetails();
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setReturnCode(-39997783);
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc1270107404");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource-1100020334");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setMemberID("MemberID1872299021");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setModifierID("ModifierID-1050722313");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID-742746522");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber1337238457");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setPlanDesc("PlanDesc136425603");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setLobID("LobID-1958753610");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setLobIDDesc("LobIDDesc1641333145");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setProgramTypeCd("ProgramTypeCd285292520");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setClassID("ClassID-1710205203");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setClassIDDesc("ClassIDDesc596807363");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt1831963781");
            _returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt-2029778208");
            _returnEligibilityInfoMedicaidMemberEligibilityDetails.add(_returnEligibilityInfoMedicaidMemberEligibilityDetailsVal1);
            _returnEligibilityInfo.getMedicaidMemberEligibilityDetails().addAll(_returnEligibilityInfoMedicaidMemberEligibilityDetails);
            _returnEligibilityInfo.setErrorMsg("ErrorMsg1189153949");
            _return.setEligibilityInfo(_returnEligibilityInfo);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityService#getEligibleMcaidMembersByMbrIDAndClient(java.lang.String  eligStrtDt ,)java.lang.String  eligEndDt ,)java.lang.String  clientName ,)java.lang.String  memberID ,)java.lang.String  modifierID ,)com.optum.rqns.services.medicareEligiblityProd.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityInfo getEligibleMcaidMembersByMbrIDAndClient(java.lang.String eligStrtDt,java.lang.String eligEndDt,java.lang.String clientName,java.lang.String memberID,java.lang.String modifierID,com.optum.rqns.services.medicareEligiblityProd.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleMcaidMembersByMbrIDAndClient");
        System.out.println(eligStrtDt);
        System.out.println(eligEndDt);
        System.out.println(clientName);
        System.out.println(memberID);
        System.out.println(modifierID);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityInfo _return = new com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityDetails> _returnMedicaidMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityDetails>();
            com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityDetails _returnMedicaidMemberEligibilityDetailsVal1 = new com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityDetails();
            _returnMedicaidMemberEligibilityDetailsVal1.setReturnCode(-255108796);
            _returnMedicaidMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc-1028884078");
            _returnMedicaidMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource1015237052");
            _returnMedicaidMemberEligibilityDetailsVal1.setMemberID("MemberID-59643363");
            _returnMedicaidMemberEligibilityDetailsVal1.setModifierID("ModifierID-240826848");
            _returnMedicaidMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID-938711528");
            _returnMedicaidMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber-78649719");
            _returnMedicaidMemberEligibilityDetailsVal1.setPlanDesc("PlanDesc823042603");
            _returnMedicaidMemberEligibilityDetailsVal1.setLobID("LobID-412113743");
            _returnMedicaidMemberEligibilityDetailsVal1.setLobIDDesc("LobIDDesc-2111134975");
            _returnMedicaidMemberEligibilityDetailsVal1.setProgramTypeCd("ProgramTypeCd2050911771");
            _returnMedicaidMemberEligibilityDetailsVal1.setClassID("ClassID2112881924");
            _returnMedicaidMemberEligibilityDetailsVal1.setClassIDDesc("ClassIDDesc-1460145224");
            _returnMedicaidMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt-136285267");
            _returnMedicaidMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt-1904810210");
            _returnMedicaidMemberEligibilityDetails.add(_returnMedicaidMemberEligibilityDetailsVal1);
            _return.getMedicaidMemberEligibilityDetails().addAll(_returnMedicaidMemberEligibilityDetails);
            _return.setErrorMsg("ErrorMsg1595536357");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
