
package com.optum.rqns.services.medicareEligiblityProd;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-11T17:09:05.858+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class MedicaidMemberEligibilityService_MedicaidMemberEligibilityServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "medicaidMemberEligibilityService");

    private MedicaidMemberEligibilityService_MedicaidMemberEligibilityServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MedicaidMemberEligibilityService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MedicaidMemberEligibilityService_Service ss = new MedicaidMemberEligibilityService_Service(wsdlURL, SERVICE_NAME);
        MedicaidMemberEligibilityService port = ss.getMedicaidMemberEligibilityServiceImplPort();  
        
        {
        System.out.println("Invoking getEligibleMcaidMembersByGlbMbrIDAndClient...");
        com.optum.rqns.services.medicareEligiblityProd.GetEligibleMcaidMembersByGlbMbrIDAndClient _getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClient = new com.optum.rqns.services.medicareEligiblityProd.GetEligibleMcaidMembersByGlbMbrIDAndClient();
        _getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClient.setEligStrtDt("EligStrtDt-1174540727");
        _getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClient.setEligEndDt("EligEndDt483217453");
        _getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClient.setClientName("ClientName1133205720");
        _getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClient.setGlobalMemberID("GlobalMemberID-1320859278");
        com.optum.rqns.services.medicareEligiblityProd.ServiceMetaData _getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClientMetaData = new com.optum.rqns.services.medicareEligiblityProd.ServiceMetaData();
        _getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClientMetaData.setAppId("AppId-1012832123");
        _getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClient.setMetaData(_getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClientMetaData);
        try {
            com.optum.rqns.services.medicareEligiblityProd.GetEligibleMcaidMembersByGlbMbrIDAndClientResponse _getEligibleMcaidMembersByGlbMbrIDAndClient__return = port.getEligibleMcaidMembersByGlbMbrIDAndClient(_getEligibleMcaidMembersByGlbMbrIDAndClient_getEligibleMcaidMembersByGlbMbrIDAndClient);
            System.out.println("getEligibleMcaidMembersByGlbMbrIDAndClient.result=" + _getEligibleMcaidMembersByGlbMbrIDAndClient__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getEligibleMcaidMembersByMbrIDAndClient...");
        java.lang.String _getEligibleMcaidMembersByMbrIDAndClient_eligStrtDt = "_getEligibleMcaidMembersByMbrIDAndClient_eligStrtDt-411562116";
        java.lang.String _getEligibleMcaidMembersByMbrIDAndClient_eligEndDt = "_getEligibleMcaidMembersByMbrIDAndClient_eligEndDt1705205594";
        java.lang.String _getEligibleMcaidMembersByMbrIDAndClient_clientName = "_getEligibleMcaidMembersByMbrIDAndClient_clientName303567368";
        java.lang.String _getEligibleMcaidMembersByMbrIDAndClient_memberID = "_getEligibleMcaidMembersByMbrIDAndClient_memberID-865979373";
        java.lang.String _getEligibleMcaidMembersByMbrIDAndClient_modifierID = "_getEligibleMcaidMembersByMbrIDAndClient_modifierID344996286";
        com.optum.rqns.services.medicareEligiblityProd.ServiceMetaData _getEligibleMcaidMembersByMbrIDAndClient_metaData = new com.optum.rqns.services.medicareEligiblityProd.ServiceMetaData();
        _getEligibleMcaidMembersByMbrIDAndClient_metaData.setAppId("AppId1186615463");
        try {
            com.optum.rqns.services.medicareEligiblityProd.MedicaidMemberEligibilityInfo _getEligibleMcaidMembersByMbrIDAndClient__return = port.getEligibleMcaidMembersByMbrIDAndClient(_getEligibleMcaidMembersByMbrIDAndClient_eligStrtDt, _getEligibleMcaidMembersByMbrIDAndClient_eligEndDt, _getEligibleMcaidMembersByMbrIDAndClient_clientName, _getEligibleMcaidMembersByMbrIDAndClient_memberID, _getEligibleMcaidMembersByMbrIDAndClient_modifierID, _getEligibleMcaidMembersByMbrIDAndClient_metaData);
            System.out.println("getEligibleMcaidMembersByMbrIDAndClient.result=" + _getEligibleMcaidMembersByMbrIDAndClient__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
