
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.medicareDemography;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T14:52:04.671+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "memberDemographicService",
                      portName = "MemberDemographicServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/rqns-services-web/services/memberDemographicService?wsdl",
                      endpointInterface = "com.optum.rqns.services.medicareDemography.MemberDemographicService")
                      
public class MemberDemographicServiceImpl implements MemberDemographicService {

    private static final Logger LOG = Logger.getLogger(MemberDemographicServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicareDemography.MemberDemographicService#getMedicareMemberLatestDemographicInfo(java.lang.String  mbrHicNbr ,)java.lang.String  clientId ,)com.optum.rqns.services.medicareDemography.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo getMedicareMemberLatestDemographicInfo(java.lang.String mbrHicNbr,java.lang.String clientId,com.optum.rqns.services.medicareDemography.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getMedicareMemberLatestDemographicInfo");
        System.out.println(mbrHicNbr);
        System.out.println(clientId);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo _return = new com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo();
            _return.setClientId("ClientId-1441290794");
            _return.setMbrCardId("MbrCardId1862657421");
            _return.setBaseMbrId("BaseMbrId-1387565103");
            _return.setMbrHicNbr("MbrHicNbr1282659741");
            _return.setMbrId("MbrId-794302423");
            _return.setMbrModId("MbrModId889416047");
            _return.setMbrFstNm("MbrFstNm-1882988762");
            _return.setMbrLstNm("MbrLstNm1936547824");
            _return.setMbrMidlNm("MbrMidlNm2099022062");
            _return.setMbrGdrCd("MbrGdrCd530149860");
            _return.setMbrDob("MbrDob-2138694497");
            _return.setMbrDod("MbrDod-548812549");
            _return.setMbrLang("MbrLang716204385");
            _return.setMaritalSts("MaritalSts1342275859");
            _return.setAddrLn1("AddrLn1-2133433856");
            _return.setAddrLn2("AddrLn21080585022");
            _return.setCity("City705590268");
            _return.setCounty("County1937779016");
            _return.setState("State1356926277");
            _return.setZipCd("ZipCd-838088240");
            _return.setExtZipCd("ExtZipCd-472216586");
            _return.setPhoneNbr("PhoneNbr1687396396");
            _return.setAltPhoneNbr("AltPhoneNbr-1262484028");
            _return.setMbrContrNbr("MbrContrNbr-139200329");
            _return.setMbrSubPlnId("MbrSubPlnId-1688506101");
            _return.setMbrGlbId("MbrGlbId-1600401098");
            _return.setClntSrcSysNm("ClntSrcSysNm680447891");
            _return.setClntSubSrcSysNm("ClntSubSrcSysNm-1287211399");
            _return.setClntDvsnNm("ClntDvsnNm-1460102270");
            _return.setMbrOrigStrtDt("MbrOrigStrtDt-1899191455");
            _return.setMbrLtEndDt("MbrLtEndDt438432038");
            _return.setMbrPoaFstNm("MbrPoaFstNm-1062794510");
            _return.setMbrPoaLstNm("MbrPoaLstNm-1108650900");
            _return.setMbrPoaRelCd("MbrPoaRelCd-988649953");
            _return.setMbrPoaTelNumTxt("MbrPoaTelNumTxt-2128834755");
            _return.setPartAEligEffDt("PartAEligEffDt1126661992");
            _return.setPartBEligEffDt("PartBEligEffDt-491614679");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicareDemography.MemberDemographicService#getMedicareMemberListInfoByHicId(java.lang.String  mbrHicNum ,)java.lang.String  clientId ,)com.optum.rqns.services.medicareDemography.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfoList getMedicareMemberListInfoByHicId(java.lang.String mbrHicNum,java.lang.String clientId,com.optum.rqns.services.medicareDemography.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getMedicareMemberListInfoByHicId");
        System.out.println(mbrHicNum);
        System.out.println(clientId);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfoList _return = new com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfoList();
            java.util.List<com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo> _returnMemberDemographicInfo = new java.util.ArrayList<com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo>();
            com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo _returnMemberDemographicInfoVal1 = new com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo();
            _returnMemberDemographicInfoVal1.setClientId("ClientId-2053400179");
            _returnMemberDemographicInfoVal1.setMbrCardId("MbrCardId-999726340");
            _returnMemberDemographicInfoVal1.setBaseMbrId("BaseMbrId1147093980");
            _returnMemberDemographicInfoVal1.setMbrHicNbr("MbrHicNbr-322092752");
            _returnMemberDemographicInfoVal1.setMbrId("MbrId-885357081");
            _returnMemberDemographicInfoVal1.setMbrModId("MbrModId-456495525");
            _returnMemberDemographicInfoVal1.setMbrFstNm("MbrFstNm-207891038");
            _returnMemberDemographicInfoVal1.setMbrLstNm("MbrLstNm-2043195122");
            _returnMemberDemographicInfoVal1.setMbrMidlNm("MbrMidlNm1191466557");
            _returnMemberDemographicInfoVal1.setMbrGdrCd("MbrGdrCd562369216");
            _returnMemberDemographicInfoVal1.setMbrDob("MbrDob1991113523");
            _returnMemberDemographicInfoVal1.setMbrDod("MbrDod1046560174");
            _returnMemberDemographicInfoVal1.setMbrLang("MbrLang-2051364250");
            _returnMemberDemographicInfoVal1.setMaritalSts("MaritalSts-463049239");
            _returnMemberDemographicInfoVal1.setAddrLn1("AddrLn1-1385551550");
            _returnMemberDemographicInfoVal1.setAddrLn2("AddrLn2-1457838885");
            _returnMemberDemographicInfoVal1.setCity("City451400757");
            _returnMemberDemographicInfoVal1.setCounty("County-4841201");
            _returnMemberDemographicInfoVal1.setState("State2116134156");
            _returnMemberDemographicInfoVal1.setZipCd("ZipCd1081071619");
            _returnMemberDemographicInfoVal1.setExtZipCd("ExtZipCd-1452985365");
            _returnMemberDemographicInfoVal1.setPhoneNbr("PhoneNbr-647240120");
            _returnMemberDemographicInfoVal1.setAltPhoneNbr("AltPhoneNbr-807733260");
            _returnMemberDemographicInfoVal1.setMbrContrNbr("MbrContrNbr-1963652546");
            _returnMemberDemographicInfoVal1.setMbrSubPlnId("MbrSubPlnId545679339");
            _returnMemberDemographicInfoVal1.setMbrGlbId("MbrGlbId1432262700");
            _returnMemberDemographicInfoVal1.setClntSrcSysNm("ClntSrcSysNm-999978930");
            _returnMemberDemographicInfoVal1.setClntSubSrcSysNm("ClntSubSrcSysNm752999053");
            _returnMemberDemographicInfoVal1.setClntDvsnNm("ClntDvsnNm-1315224652");
            _returnMemberDemographicInfoVal1.setMbrOrigStrtDt("MbrOrigStrtDt1651085243");
            _returnMemberDemographicInfoVal1.setMbrLtEndDt("MbrLtEndDt-1446155398");
            _returnMemberDemographicInfoVal1.setMbrPoaFstNm("MbrPoaFstNm-947044762");
            _returnMemberDemographicInfoVal1.setMbrPoaLstNm("MbrPoaLstNm908444170");
            _returnMemberDemographicInfoVal1.setMbrPoaRelCd("MbrPoaRelCd1458535550");
            _returnMemberDemographicInfoVal1.setMbrPoaTelNumTxt("MbrPoaTelNumTxt1701954869");
            _returnMemberDemographicInfoVal1.setPartAEligEffDt("PartAEligEffDt1695158384");
            _returnMemberDemographicInfoVal1.setPartBEligEffDt("PartBEligEffDt-884971914");
            _returnMemberDemographicInfo.add(_returnMemberDemographicInfoVal1);
            _return.getMemberDemographicInfo().addAll(_returnMemberDemographicInfo);
            _return.setErrorCd(Integer.valueOf(-2047862037));
            _return.setErrorMsg("ErrorMsg1280395307");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.medicareDemography.MemberDemographicService#getMedicareMemberListInfoByCardId(java.lang.String  mbrCardId ,)java.lang.String  clientId ,)com.optum.rqns.services.medicareDemography.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfoList getMedicareMemberListInfoByCardId(java.lang.String mbrCardId,java.lang.String clientId,com.optum.rqns.services.medicareDemography.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getMedicareMemberListInfoByCardId");
        System.out.println(mbrCardId);
        System.out.println(clientId);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfoList _return = new com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfoList();
            java.util.List<com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo> _returnMemberDemographicInfo = new java.util.ArrayList<com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo>();
            com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo _returnMemberDemographicInfoVal1 = new com.optum.rqns.services.medicareDemography.MedicareMemberDemographicInfo();
            _returnMemberDemographicInfoVal1.setClientId("ClientId749651850");
            _returnMemberDemographicInfoVal1.setMbrCardId("MbrCardId-846937615");
            _returnMemberDemographicInfoVal1.setBaseMbrId("BaseMbrId156790029");
            _returnMemberDemographicInfoVal1.setMbrHicNbr("MbrHicNbr-918180913");
            _returnMemberDemographicInfoVal1.setMbrId("MbrId229841425");
            _returnMemberDemographicInfoVal1.setMbrModId("MbrModId-1719071013");
            _returnMemberDemographicInfoVal1.setMbrFstNm("MbrFstNm-292857500");
            _returnMemberDemographicInfoVal1.setMbrLstNm("MbrLstNm1142958959");
            _returnMemberDemographicInfoVal1.setMbrMidlNm("MbrMidlNm1055789410");
            _returnMemberDemographicInfoVal1.setMbrGdrCd("MbrGdrCd721885234");
            _returnMemberDemographicInfoVal1.setMbrDob("MbrDob698012681");
            _returnMemberDemographicInfoVal1.setMbrDod("MbrDod824599170");
            _returnMemberDemographicInfoVal1.setMbrLang("MbrLang-94154339");
            _returnMemberDemographicInfoVal1.setMaritalSts("MaritalSts120446975");
            _returnMemberDemographicInfoVal1.setAddrLn1("AddrLn1-1064831467");
            _returnMemberDemographicInfoVal1.setAddrLn2("AddrLn21485838916");
            _returnMemberDemographicInfoVal1.setCity("City-789145172");
            _returnMemberDemographicInfoVal1.setCounty("County-1597851373");
            _returnMemberDemographicInfoVal1.setState("State-194861245");
            _returnMemberDemographicInfoVal1.setZipCd("ZipCd1721490564");
            _returnMemberDemographicInfoVal1.setExtZipCd("ExtZipCd-1299660925");
            _returnMemberDemographicInfoVal1.setPhoneNbr("PhoneNbr1573767155");
            _returnMemberDemographicInfoVal1.setAltPhoneNbr("AltPhoneNbr545766868");
            _returnMemberDemographicInfoVal1.setMbrContrNbr("MbrContrNbr-405184580");
            _returnMemberDemographicInfoVal1.setMbrSubPlnId("MbrSubPlnId825339048");
            _returnMemberDemographicInfoVal1.setMbrGlbId("MbrGlbId-1848041712");
            _returnMemberDemographicInfoVal1.setClntSrcSysNm("ClntSrcSysNm315013298");
            _returnMemberDemographicInfoVal1.setClntSubSrcSysNm("ClntSubSrcSysNm-2019155870");
            _returnMemberDemographicInfoVal1.setClntDvsnNm("ClntDvsnNm1065295606");
            _returnMemberDemographicInfoVal1.setMbrOrigStrtDt("MbrOrigStrtDt-1937184197");
            _returnMemberDemographicInfoVal1.setMbrLtEndDt("MbrLtEndDt-1608091688");
            _returnMemberDemographicInfoVal1.setMbrPoaFstNm("MbrPoaFstNm-641090691");
            _returnMemberDemographicInfoVal1.setMbrPoaLstNm("MbrPoaLstNm1507340701");
            _returnMemberDemographicInfoVal1.setMbrPoaRelCd("MbrPoaRelCd1841716567");
            _returnMemberDemographicInfoVal1.setMbrPoaTelNumTxt("MbrPoaTelNumTxt-1282238736");
            _returnMemberDemographicInfoVal1.setPartAEligEffDt("PartAEligEffDt551870074");
            _returnMemberDemographicInfoVal1.setPartBEligEffDt("PartBEligEffDt-1633553812");
            _returnMemberDemographicInfo.add(_returnMemberDemographicInfoVal1);
            _return.getMemberDemographicInfo().addAll(_returnMemberDemographicInfo);
            _return.setErrorCd(Integer.valueOf(-568436145));
            _return.setErrorMsg("ErrorMsg1815170621");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
