
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.eligiblity;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-07-25T16:40:21.690+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "AcaMemberEligibilityService",
                      portName = "AcaMemberEligibilityServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/dev/rqns-services-web/services/AcaMemberEligibilityService?wsdl",
                      endpointInterface = "com.optum.rqns.services.eligiblity.AcaMemberEligibilityService")
                      
public class AcaMemberEligibilityServiceImpl implements AcaMemberEligibilityService {

    private static final Logger LOG = Logger.getLogger(AcaMemberEligibilityServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.eligiblity.AcaMemberEligibilityService#getEligibleAcaMembersByMbrIDAndClient(java.lang.String  memberID ,)java.lang.String  modifierID ,)java.lang.String  clientName ,)java.lang.String  eligStrtDt ,)java.lang.String  eligEndDt ,)com.optum.rqns.services.eligiblity.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.eligiblity.AcaMemberEligibilityInfo getEligibleAcaMembersByMbrIDAndClient(java.lang.String memberID,java.lang.String modifierID,java.lang.String clientName,java.lang.String eligStrtDt,java.lang.String eligEndDt,com.optum.rqns.services.eligiblity.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleAcaMembersByMbrIDAndClient");
        System.out.println(memberID);
        System.out.println(modifierID);
        System.out.println(clientName);
        System.out.println(eligStrtDt);
        System.out.println(eligEndDt);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.eligiblity.AcaMemberEligibilityInfo _return = new com.optum.rqns.services.eligiblity.AcaMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.eligiblity.AcaMemberEligibilityDetails> _returnAcaMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.eligiblity.AcaMemberEligibilityDetails>();
            com.optum.rqns.services.eligiblity.AcaMemberEligibilityDetails _returnAcaMemberEligibilityDetailsVal1 = new com.optum.rqns.services.eligiblity.AcaMemberEligibilityDetails();
            _returnAcaMemberEligibilityDetailsVal1.setReturnCode(-87945948);
            _returnAcaMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc-1890941460");
            _returnAcaMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource1447327052");
            _returnAcaMemberEligibilityDetailsVal1.setClientGuid("ClientGuid-73793600");
            _returnAcaMemberEligibilityDetailsVal1.setMemberID("MemberID-1728729786");
            _returnAcaMemberEligibilityDetailsVal1.setModifierID("ModifierID-1383560916");
            _returnAcaMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID-2056780662");
            _returnAcaMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber1496417056");
            _returnAcaMemberEligibilityDetailsVal1.setMetalLevel("MetalLevel-1562152981");
            _returnAcaMemberEligibilityDetailsVal1.setSubscriberID("SubscriberID1978006091");
            _returnAcaMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt-874658467");
            _returnAcaMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt894527505");
            _returnAcaMemberEligibilityDetailsVal1.setEmpGroupID("EmpGroupID1898779217");
            _returnAcaMemberEligibilityDetails.add(_returnAcaMemberEligibilityDetailsVal1);
            _return.getAcaMemberEligibilityDetails().addAll(_returnAcaMemberEligibilityDetails);
            _return.setErrorMsg("ErrorMsg1639083913");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.optum.rqns.services.eligiblity.AcaMemberEligibilityService#getEligibleAcaMembersByGlbMbrIDAndClient(java.lang.String  globalMemberID ,)java.lang.String  clientName ,)java.lang.String  eligStrtDt ,)java.lang.String  eligEndDt ,)com.optum.rqns.services.eligiblity.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.eligiblity.AcaMemberEligibilityInfo getEligibleAcaMembersByGlbMbrIDAndClient(java.lang.String globalMemberID,java.lang.String clientName,java.lang.String eligStrtDt,java.lang.String eligEndDt,com.optum.rqns.services.eligiblity.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getEligibleAcaMembersByGlbMbrIDAndClient");
        System.out.println(globalMemberID);
        System.out.println(clientName);
        System.out.println(eligStrtDt);
        System.out.println(eligEndDt);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.eligiblity.AcaMemberEligibilityInfo _return = new com.optum.rqns.services.eligiblity.AcaMemberEligibilityInfo();
            java.util.List<com.optum.rqns.services.eligiblity.AcaMemberEligibilityDetails> _returnAcaMemberEligibilityDetails = new java.util.ArrayList<com.optum.rqns.services.eligiblity.AcaMemberEligibilityDetails>();
            com.optum.rqns.services.eligiblity.AcaMemberEligibilityDetails _returnAcaMemberEligibilityDetailsVal1 = new com.optum.rqns.services.eligiblity.AcaMemberEligibilityDetails();
            _returnAcaMemberEligibilityDetailsVal1.setReturnCode(1534613462);
            _returnAcaMemberEligibilityDetailsVal1.setReturnCodeDesc("ReturnCodeDesc-1568779216");
            _returnAcaMemberEligibilityDetailsVal1.setEligibilitySource("EligibilitySource-1743102682");
            _returnAcaMemberEligibilityDetailsVal1.setClientGuid("ClientGuid74155053");
            _returnAcaMemberEligibilityDetailsVal1.setMemberID("MemberID1938772051");
            _returnAcaMemberEligibilityDetailsVal1.setModifierID("ModifierID451356252");
            _returnAcaMemberEligibilityDetailsVal1.setGlobalMemberID("GlobalMemberID-1078041062");
            _returnAcaMemberEligibilityDetailsVal1.setPlanNumber("PlanNumber1492434050");
            _returnAcaMemberEligibilityDetailsVal1.setMetalLevel("MetalLevel609674551");
            _returnAcaMemberEligibilityDetailsVal1.setSubscriberID("SubscriberID-1397119919");
            _returnAcaMemberEligibilityDetailsVal1.setEnrlEndDt("EnrlEndDt-482945361");
            _returnAcaMemberEligibilityDetailsVal1.setEnrlBegDt("EnrlBegDt-1399118302");
            _returnAcaMemberEligibilityDetailsVal1.setEmpGroupID("EmpGroupID1477985245");
            _returnAcaMemberEligibilityDetails.add(_returnAcaMemberEligibilityDetailsVal1);
            _return.getAcaMemberEligibilityDetails().addAll(_returnAcaMemberEligibilityDetails);
            _return.setErrorMsg("ErrorMsg1818353301");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
