package com.optum.rqns.services.supplementalTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * The service port type for SupplementalInfoService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-02T12:44:17.421+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://services.rqns.optum.com/", name = "SupplementalInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface SupplementalInfoService {

    /**
     * The operation saves supplemental information
     */
    @WebMethod(action = "addSupplementalInfo")
    @RequestWrapper(localName = "addSupplementalInfo", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.supplementalTest.AddSupplementalInfo")
    @ResponseWrapper(localName = "addSupplementalInfoResponse", targetNamespace = "http://services.rqns.optum.com/", className = "com.optum.rqns.services.supplementalTest.AddSupplementalInfoResponse")
    public void addSupplementalInfo(
        @WebParam(name = "serviceMetaData", targetNamespace = "")
        com.optum.rqns.services.supplementalTest.ServiceMetaData serviceMetaData,
        @WebParam(name = "supplementalInfo", targetNamespace = "")
        com.optum.rqns.services.supplementalTest.SupplementalInfo supplementalInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> responseCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseMessage", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> responseMessage
    ) throws ServiceException_Exception;
}
