
package com.optum.rqns.services.supplementalTest;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.optum.rqns.services.utils.DataBaseConnect;



/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-02T12:44:17.261+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class SupplementalInfoService_SupplementalInfoServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.rqns.optum.com/", "SupplementalInfoService");
 
	 private static  com.optum.rqns.services.supplementalTest.ServiceMetaData _addSupplementalInfo_serviceMetaData=null;
	    private static  com.optum.rqns.services.supplementalTest.SupplementalInfo _addSupplementalInfo_supplementalInfo=null;
    public SupplementalInfoService_SupplementalInfoServiceImplPort_Client() {
    	
    }

    public  String supplementalService() throws java.lang.Exception {
    	String sRandomId;
    	 
    	
        
        URL wsdlURL = SupplementalInfoService_Service.WSDL_LOCATION;
      
      
        SupplementalInfoService_Service ss = new SupplementalInfoService_Service(wsdlURL, SERVICE_NAME);
        SupplementalInfoService port = ss.getSupplementalInfoServiceImplPort();  
        
        {
        	
        	 sRandomId=DataBaseConnect.makeIdUsingTime("yyyyMMddHHmmss");
        	
      
        	 
        	 
        	  System.out.println("Invoking addSupplementalInfo...");
              _addSupplementalInfo_serviceMetaData = new com.optum.rqns.services.supplementalTest.ServiceMetaData();
              _addSupplementalInfo_serviceMetaData.setAppId("9032afa9f3e34e6fd0e05e967be021f7");
             // _addSupplementalInfo_serviceMetaData.setAppId("a1f1e49c9d7191ad667192b8a0f601d2");
              _addSupplementalInfo_supplementalInfo = new com.optum.rqns.services.supplementalTest.SupplementalInfo();
              _addSupplementalInfo_supplementalInfo.setSrcSsys("RQNS.CareManager");
              _addSupplementalInfo_supplementalInfo.setClntGuid("c3f51d7a-2e1b-487c-888f-52a765bf1b63");
              _addSupplementalInfo_supplementalInfo.setMemberId("M"+sRandomId);
              _addSupplementalInfo_supplementalInfo.setMemberGlbId("");
              _addSupplementalInfo_supplementalInfo.setMemberAltTypeCd("CLIENT");
              _addSupplementalInfo_supplementalInfo.setMemberAltIdValtxt("M1362500008");
              _addSupplementalInfo_supplementalInfo.setSupplDataType("FOC_01");
              _addSupplementalInfo_supplementalInfo.setSupplDataCd("A1c (rslts)");
              _addSupplementalInfo_supplementalInfo.setSupplDos("20170707100908");
              _addSupplementalInfo_supplementalInfo.setSupplDataValTxt("33");
              _addSupplementalInfo_supplementalInfo.setSupplDataNum("33");
              _addSupplementalInfo_supplementalInfo.setSupplDataUnit("");
              _addSupplementalInfo_supplementalInfo.setTransTimeStamp("20170707100908");
              _addSupplementalInfo_supplementalInfo.setUsrOptumId("sjha1002");
              _addSupplementalInfo_supplementalInfo.setUsrLastName("Jha");
              _addSupplementalInfo_supplementalInfo.setUserFirstName("Shiv");
              _addSupplementalInfo_supplementalInfo.setRecordStatus("Y");
              javax.xml.ws.Holder<java.lang.Integer> _addSupplementalInfo_responseCode = new javax.xml.ws.Holder<java.lang.Integer>();
              javax.xml.ws.Holder<java.lang.String> _addSupplementalInfo_responseMessage = new javax.xml.ws.Holder<java.lang.String>();
              try {
                  port.addSupplementalInfo(_addSupplementalInfo_serviceMetaData, _addSupplementalInfo_supplementalInfo, _addSupplementalInfo_responseCode, _addSupplementalInfo_responseMessage);

                  System.out.println("addSupplementalInfo._addSupplementalInfo_responseCode=" + _addSupplementalInfo_responseCode.value);
                  System.out.println("addSupplementalInfo._addSupplementalInfo_responseMessage=" + _addSupplementalInfo_responseMessage.value);
              } catch (ServiceException_Exception e) { 
                  System.out.println("Expected exception: ServiceException has occurred.");
                  System.out.println(e.toString());
              }
              
        	 
        	 
        
            }
       // Thread.sleep(3000);
        //sRandomId="20170704053851";
        System.out.println("Member id :- "+"M"+sRandomId);
        ResultSet rs=DataBaseConnect.getRsList("TEST-DW", "select count(*) from A_suppl_scr_data where MBR_id='"+"M"+sRandomId+"'");
       int iCount=0;
        while (rs.next()){
        	iCount = rs.getInt(1);
        }
        
        if (iCount==1)
        {
        	ResultSet rs1=DataBaseConnect.getRsList("TEST-DW", "select * from A_suppl_scr_data where MBR_id='"+"M"+sRandomId+"'");
        	 while (rs1.next()){
        	/*Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSrcSsys(), rs1.getString("SRC_SYS_CD"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getClntGuid(), rs1.getString("CLI_ID"));
        	//Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSrcSsys(), rs1.getInt("CLI_SK"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getClntGuid(), rs1.getString("CLNT_GUID"));
        	//Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSrcSsys(), rs1.getInt("SUB_CLI_SK"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getMemberId(), rs1.getString("MBR_ID"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getMemberGlbId(), rs1.getString("MBR_GLB_ID"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getMemberAltTypeCd(), rs1.getString("MBR_ALT_ID_TYP_CD"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getMemberAltIdValtxt(), rs1.getString("MBR_ALT_ID_VAL_TXT"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSupplDataType(), rs1.getString("SUPPL_DATA_TYP"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSupplDataCd(), rs1.getString("SUPPL_DATA_CD"));
        	//Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSrcSsys(), rs1.getDate("SUPPL_DOS"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSupplDataValTxt(), rs1.getString("SUPPL_DATA_VAL_TXT"));
        	//Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSrcSsys(), rs1.getInt("SUPPL_DATA_NUM"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSupplDataUnit(), rs1.getString("SUPPL_DATA_UNIT"));
        	//Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getSrcSsys(), rs1.getTimestamp("TRANS_TIMESTAMP"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getUsrOptumId(), rs1.getString("USR_OPTUM_ID"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getUsrLastName(), rs1.getString("USR_LST_NM"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getUserFirstName(), rs1.getString("USR_FST_NM"));
        	Verify.verifyEqual(_addSupplementalInfo_supplementalInfo.getRecordStatus(), rs1.getString("RECORD_STATUS"));*/
        	 }
        }
        else
        {
        	System.out.println("No record inserted with mbr id:"+ "M"+sRandomId);
        }
        
        System.out.println("Record count is"+ iCount);
       // System.exit(0);
		return " Record inserted in A_suppl_scr_data table with mbr id:"+ "M"+sRandomId;
    }

}
