package com.optum.rqns.services.supplementalTest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The service name for SupplementalInfoService
 *
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-02T12:44:17.427+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "SupplementalInfoService", 
                  wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8444/tst/rqns-services-web/services/SupplementalInfoService?wsdl",
                  targetNamespace = "http://services.rqns.optum.com/") 
public class SupplementalInfoService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.rqns.optum.com/", "SupplementalInfoService");
    public final static QName SupplementalInfoServiceImplPort = new QName("http://services.rqns.optum.com/", "SupplementalInfoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://trustbroker-stg-svcs.optum.com:8444/tst/rqns-services-web/services/SupplementalInfoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SupplementalInfoService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://trustbroker-stg-svcs.optum.com:8444/tst/rqns-services-web/services/SupplementalInfoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SupplementalInfoService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SupplementalInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupplementalInfoService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplementalInfoService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplementalInfoService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplementalInfoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * The service port for SupplementalInfoService
     *
     * @return
     *     returns SupplementalInfoService
     */
    @WebEndpoint(name = "SupplementalInfoServiceImplPort")
    public SupplementalInfoService getSupplementalInfoServiceImplPort() {
        return super.getPort(SupplementalInfoServiceImplPort, SupplementalInfoService.class);
    }

    /**
     * The service port for SupplementalInfoService
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SupplementalInfoService
     */
    @WebEndpoint(name = "SupplementalInfoServiceImplPort")
    public SupplementalInfoService getSupplementalInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SupplementalInfoServiceImplPort, SupplementalInfoService.class, features);
    }

}
