
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.optum.rqns.services.rxClaimsLookupTest;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-07T14:57:27.977+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "RXClaimsLookUpService",
                      portName = "RXClaimsLookUpServiceImplPort",
                      targetNamespace = "http://services.rqns.optum.com/",
                      wsdlLocation = "https://trustbroker-stg-svcs.optum.com:8443/tst/rqns-services-web/services/RXClaimsLookUpService?wsdl",
                      endpointInterface = "com.optum.rqns.services.rxClaimsLookupTest.RXClaimsLookUpService")
                      
public class RXClaimsLookUpServiceImpl implements RXClaimsLookUpService {

    private static final Logger LOG = Logger.getLogger(RXClaimsLookUpServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.optum.rqns.services.rxClaimsLookupTest.RXClaimsLookUpService#getRXClaimsByMbrIDAndClient(java.lang.String  memberIdentifier ,)java.lang.String  memberModifier ,)java.lang.String  clientGuid ,)com.optum.rqns.services.rxClaimsLookupTest.ServiceMetaData  metaData )*
     */
    public com.optum.rqns.services.rxClaimsLookupTest.RxClaimsInfo getRXClaimsByMbrIDAndClient(java.lang.String memberIdentifier,java.lang.String memberModifier,java.lang.String clientGuid,com.optum.rqns.services.rxClaimsLookupTest.ServiceMetaData metaData) throws ServiceException_Exception    { 
        LOG.info("Executing operation getRXClaimsByMbrIDAndClient");
        System.out.println(memberIdentifier);
        System.out.println(memberModifier);
        System.out.println(clientGuid);
        System.out.println(metaData);
        try {
            com.optum.rqns.services.rxClaimsLookupTest.RxClaimsInfo _return = new com.optum.rqns.services.rxClaimsLookupTest.RxClaimsInfo();
            _return.setReturnCode(Integer.valueOf(652848249));
            _return.setReturnCodeDesc("ReturnCodeDesc-2147450952");
            java.util.List<com.optum.rqns.services.rxClaimsLookupTest.RxClaimDetails> _returnRxClaimDetails = new java.util.ArrayList<com.optum.rqns.services.rxClaimsLookupTest.RxClaimDetails>();
            com.optum.rqns.services.rxClaimsLookupTest.RxClaimDetails _returnRxClaimDetailsVal1 = new com.optum.rqns.services.rxClaimsLookupTest.RxClaimDetails();
            _returnRxClaimDetailsVal1.setMemberGlobalId("MemberGlobalId-1517057673");
            _returnRxClaimDetailsVal1.setMemberIdentifier("MemberIdentifier-259005866");
            _returnRxClaimDetailsVal1.setMemberModifierId("MemberModifierId-155716237");
            _returnRxClaimDetailsVal1.setNdcDesc("NdcDesc988834171");
            _returnRxClaimDetailsVal1.setNdcCode("NdcCode-643132788");
            _returnRxClaimDetailsVal1.setDateFilled(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-08-07T14:57:27.987+05:30"));
            _returnRxClaimDetailsVal1.setQuantity("Quantity-2029973877");
            _returnRxClaimDetailsVal1.setDateSupply("DateSupply-354488629");
            _returnRxClaimDetailsVal1.setProviderFirstName("ProviderFirstName-1148569071");
            _returnRxClaimDetailsVal1.setProviderLastName("ProviderLastName1717120569");
            _returnRxClaimDetailsVal1.setProviderMiddleName("ProviderMiddleName911075660");
            _returnRxClaimDetails.add(_returnRxClaimDetailsVal1);
            _return.getRxClaimDetails().addAll(_returnRxClaimDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException_Exception("ServiceException...");
    }

}
